### ISSUE TITLE
无法添加图片和附件

### ISSUE THREAD

**Issue by AsherHuu** [mylxsw/wizard#102]
![image](https://user-images.githubusercontent.com/32830348/86224342-53f40180-bbbb-11ea-8292-ddf185b7e86a.png)

**Comment by AsherHuu** [comment]
![image](https://user-images.githubusercontent.com/32830348/86224421-7128d000-bbbb-11ea-9f2a-1c43be91773f.png)
附件上传以后跳转到了一个500的页面

**Comment by AsherHuu** [comment]
![image](https://user-images.githubusercontent.com/32830348/86224592-a6352280-bbbb-11ea-8c9d-cc88754868ae.png)

**Comment by AsherHuu** [comment]
![image](https://user-images.githubusercontent.com/32830348/86306386-bba35e80-bc46-11ea-8a79-54acaed900e4.png)

**Comment by mylxsw** [comment]
运行 PHP 的用户需要有 storage/app/public 目录的写入权限，项目根目录执行 `chmod -R 777 storage/app/public`

**Comment by AsherHuu** [comment]
docker 容器部署的需要进入docker容器执行chmod -R 777 storage/app/public，否则会因为文件夹权限问题导致无法上传本地图片和附件
