### ISSUE TITLE
ldap账户集成遇到的问题

### ISSUE THREAD

**Issue by mrochcn** [mylxsw/wizard#105]
关于ldap的配置是按照issues15中的推荐进行的配置
[https://github.com/mylxsw/wizard/issues/15](url)
配置完之后执行
php artisan adldap:import -vvv
之后用户中会正常添加ldap中的用户，
但是使用用户的邮箱登录的时候就会报账户信息不合法。
docker log相关容器的到的日志如下

`172.17.0.1 - - [07/Aug/2020:12:03:09 +0000] "GET /login HTTP/1.1" 200 2484 "http://127.0.0.1:8066/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
172.17.0.1 - - [07/Aug/2020:12:03:27 +0000] "POST /login HTTP/1.1" 302 1348 "http://127.0.0.1:8066/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
172.17.0.1 - - [07/Aug/2020:12:03:27 +0000] "GET /login HTTP/1.1" 200 2570 "http://127.0.0.1:8066/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"`

ldap的相关配置如下

`WIZARD_USE_LDAP=true  
LDAP_LOGGING=true  
LDAP_ACCOUNT_PREFIX=  
LDAP_ACCOUNT_SUFFIX=  
LDAP_HOSTS=39.98.164.69  
LDAP_PORT=389  
LDAP_BASE_DN=dc=********,dc=com  
LDAP_USERNAME= ****************,dc=com  
LDAP_PASSWORD= *********  
LDAP_USE_SSL=false  
LDAP_USE_TLS=false  
LDAP_PASSWORD_SYNC=true  
LDAP_LOGIN_FALLBACK=true  
LDAP_SYNC_NAME_ATTR=mail  

另外config文件夹中的ldap.php跟ldap_auth.php也按照issues15中下方评论的建议改了。

**Comment by mrochcn** [comment]
@mylxsw

**Comment by mylxsw** [comment]
你用的是 OpenLDAP 还是 ActiveDirectory 呢，两种方式配置起来是有些差异的，另外日志都在 storage/logs/laravel.log 里面哈

**Comment by mrochcn** [comment]
> 你用的是 OpenLDAP 还是 ActiveDirectory 呢，两种方式配置起来是有些差异的，另外日志都在 storage/logs/laravel.log 里面哈

根据日志信息成功拼接登录信息，然后成功了，感谢@mylxsw

**Comment by Justsoso9527** [comment]
你好，遇到跟你之前一样的问题，麻烦分享一下之前处理 拼接登陆信息 的配置，谢谢

**Comment by mrochcn** [comment]
> 你好，遇到跟你之前一样的问题，麻烦分享一下之前处理 拼接登陆信息 的配置，谢谢

使用登陆的时候要拼接cn=xxx,ou=******,dc=***,dc=********
配置文件里面有拼接前序跟后序
登陆的时候注意查询ldap报的log，根据log信息来调试，很快就解决了
把你想要的cn放在中间就能ok啦

**Comment by Justsoso9527** [comment]
多谢多谢   修改了ldap账号的前缀和后缀后   经过一番折腾终于搞定了
