### ISSUE TITLE
页面有一个请求超时

### ISSUE THREAD

**Issue by ihlfo** [mylxsw/wizard#108]
页面有一个请求超时
Request URL: https://aicode.cc/wizard-update/version?callback=jQuery1124021126485814608653_1598414066545&_=1598414066546

**Comment by mylxsw** [comment]
这个是用来检查版本更新的，服务器到期被回收了，所以会超时，可以在配置文件 .env 中添加配置项 `WIZARD_VERSION_CHECK=false` 来关闭自动更新。

> Docker 部署添加环境变量即可
