### ISSUE TITLE
docker-compose up部署失败

### ISSUE THREAD

**Issue by wqwangwei** [mylxsw/wizard#109]
php_1      | 
php_1      |                                                                                                                                                    
php_1      |   [Composer\Downloader\TransportException]                                                                                                         
php_1      |   The "https://packagist.laravel-china.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
php_1      |   error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed                                                             
php_1      |   Failed to enable crypto                                                                                                                          
php_1      |   failed to open stream: operation failed                                                                                                          
php_1      |                                                                                                                                                    
php_1      | 
php_1      | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
php_1      | 
nginx_1    | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx_1    | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf differs from the packaged version
nginx_1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1    | /docker-entrypoint.sh: Configuration complete; ready for start up
php_1      | 
php_1      | Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17
php_1      | 
php_1      | Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17
php_1      | 
php_1      | Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17
php_1      | 
php_1      | Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17
wizard_php_1 exited with code 255

**Comment by wqwangwei** [comment]
MAC 环境

**Comment by mylxsw** [comment]
Laravel-China 的 composer 镜像仓库关闭了，可以按照这里设置使用阿里云的镜像 https://developer.aliyun.com/composer

或者简单点，直接下载这个 https://github.com/mylxsw/wizard/releases/download/1.2.0/vendor.zip 解压到项目根目录就可以了

**Comment by niaiwomattt** [comment]
mac ，docker-compose up 启动失败

```bash
Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17
```

**Comment by mylxsw** [comment]
> mac ，docker-compose up 启动失败
> 
> ```shell
> Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17
> 
> Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17
> ```

下载这个 https://github.com/mylxsw/wizard/releases/download/1.2.0/vendor.zip 解压到项目根目录

**Comment by niaiwomattt** [comment]
> > mac ，docker-compose up 启动失败
> > ```shell
> > Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17
> > 
> > Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17
> > ```
> 
> 下载这个 https://github.com/mylxsw/wizard/releases/download/1.2.0/vendor.zip 解压到项目根目录

```bash
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wizard.wz_project_catalogs' doesn't exist (SQL: select `wz_project_catalogs`.*, (select count(*) from `wz_projects` where `wz_project_catalogs`.`id` = `wz_projects`.`catalog_id` and `wz_projects`.`deleted_at` is null) as `projects_count` from `wz_project_catalogs` where `show_in_home` = 1 order by `sort_level` asc)
```

**Comment by mylxsw** [comment]
停止服务，docker-compose down 然后清理下当前环境 docker-compose rm。

更新代码到最新，重新执行 `docker-compose up`。之前 composer 用的国内镜像已经停服了，刚刚改成其他的了，需要重新创建环境（docker-compose 环境已经很久没有动过了，刚刚试了下，改了之后就可以启动了）。

**Comment by niaiwomattt** [comment]
启动成功了，那个 php 那个 容器退出后才能正常访问，但是默认账号秘密多少 ？我登录不了！

**Comment by mylxsw** [comment]
> 启动成功了，那个 php 那个 容器退出后才能正常访问，但是默认账号秘密多少 ？我登录不了！

直接注册新用户，第一个注册的用户就是管理员。

**Comment by niaiwomattt** [comment]
ok，谢谢

**Comment by niaiwomattt** [comment]
![image](https://user-images.githubusercontent.com/2947859/92705183-16171480-f386-11ea-859e-9c550c33ba5e.png)
创建用户失败

**Comment by niaiwomattt** [comment]
性能特别差，运行起来很缓慢！

**Comment by mylxsw** [comment]
这是因为没有配置邮件发送的配置，下面几个办法可以解决（任一个都可以解决）

- 关闭邮件激活功能，在配置文件 .env 中，将 `WIZARD_NEED_ACTIVATE=true` 改为 `WIZARD_NEED_ACTIVATE=false`，然后连接到数据库，删除掉 user 表中的用户，重新注册
- 在 .env 中修改邮件发送相关的配置，发送邮件激活
- 清理环境，更新代码，最新的代码中已经将这个选项WIZARD_NEED_ACTIVATE改为了 false，不启用邮件激活

> `docker-compose` 方式仅用于测试体验，不要正式使用

**Comment by mylxsw** [comment]
> 性能特别差，运行起来很缓慢！

是的，这个 docker-compose 环境运行就是特别慢，建议直接使用 Docker 部署的方式运行。

**Comment by niaiwomattt** [comment]
但是 docker 那个我看连接的是 远程 db，怎么连接自己的db 呢 ？

**Comment by mylxsw** [comment]
配置文件中修改数据库地址就可以的，看这里 [Docker 方式安装](https://github.com/mylxsw/wizard#%E9%80%9A%E8%BF%87-docker-%E5%AE%89%E8%A3%85)

**Comment by niaiwomattt** [comment]
> 这是因为没有配置邮件发送的配置，下面几个办法可以解决（任一个都可以解决）
> 
> * 关闭邮件激活功能，在配置文件 .env 中，将 `WIZARD_NEED_ACTIVATE=true` 改为 `WIZARD_NEED_ACTIVATE=false`，然后连接到数据库，删除掉 user 表中的用户，重新注册
> * 在 .env 中修改邮件发送相关的配置，发送邮件激活
> * 清理环境，更新代码，最新的代码中已经将这个选项WIZARD_NEED_ACTIVATE改为了 false，不启用邮件激活
> 
> > `docker-compose` 方式仅用于测试体验，不要正式使用

配置文件改不了，.env 我改了好多次，一执行就全部还原了！

**Comment by mylxsw** [comment]
docker-compose up 时会重新初始化环境，所以配置文件会自动替换，非要用这个方式的话就改 docker-compose/.env.docker 吧，启动的时候就是用这个文件作为配置模板的。
