### ISSUE TITLE
运行命令php artisan migrate:install 数据库报错 ,字段不能为空

### ISSUE THREAD

**Issue by cenahui** [mylxsw/wizard#110]
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: create table `mig  
  rations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(191) not null, `batch` int not nu  
  ll) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by mylxsw** [comment]
不是字段问题哦，是你的数据库地址配置错了，连不上数据库

    php_network_getaddresses: getaddrinfo failed: Name or service not known

解决方法参考 #36 #60
