### ISSUE TITLE
是否考虑支持MarkDown文件导入功能

### ISSUE THREAD

**Issue by Andseny** [mylxsw/wizard#123]
请问大佬，是否考虑增加类似showdoc的markdown压缩包导入功能？这样从其它地方制作的.md文件就可以直接导入项目，而不用一个一个复制粘贴了。

**Comment by mylxsw** [comment]
安排

**Comment by mylxsw** [comment]
Markdown 文档批量导入功能已经上线，请看

- [Release 1.2.6](https://github.com/mylxsw/wizard/releases/tag/1.2.6)
- [开源文档管理系统 Wizard 1.2.6 发布](https://github.com/mylxsw/wizard/wiki/%E5%BC%80%E6%BA%90%E6%96%87%E6%A1%A3%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F-Wizard-1.2.6-%E5%8F%91%E5%B8%83)

**Comment by Andseny** [comment]
> Markdown 文档批量导入功能已经上线，请看
> 
> * [版本1.2.6](https://github.com/mylxsw/wizard/releases/tag/1.2.6)
> * [开源文档管理系统 Wizard 1.2.6 发布](https://github.com/mylxsw/wizard/wiki/%E5%BC%80%E6%BA%90%E6%96%87%E6%A1%A3%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F-Wizard-1.2.6-%E5%8F%91%E5%B8%83)

太厉害了，感谢！！
