### ISSUE TITLE
Docker启动失败

### ISSUE THREAD

**Issue by qiangwushuang** [mylxsw/wizard#127]
参考GitHub Readme方式，初始数据库报错：
![1](https://user-images.githubusercontent.com/6835840/102841632-4cae0200-4440-11eb-9859-236043bf874c.png)
参考DockerHub，直接运行报错500，使用调试模式登陆提示：
![2](https://user-images.githubusercontent.com/6835840/102841730-75ce9280-4440-11eb-9b02-bd972f7101ba.png)

**Comment by wanngsanchao** [comment]
同样的问题，按照readme的方式安装报错
![image](https://user-images.githubusercontent.com/66109845/102864204-b0e7ba80-446e-11eb-98af-9579bad54ce9.png)
![image](https://user-images.githubusercontent.com/66109845/102864255-c4932100-446e-11eb-9705-d2d8c62754ae.png)
应该是数据库初始化有问题

**Comment by fdtl01** [comment]
将数据库地址更改为127.0.0.1

**Comment by mylxsw** [comment]
这个问题是数据库访问地址有问题，修改将 DB_HOST 参数修改为真实的数据库连接地址，如果数据库是在宿主机上，则使用  `host.docker.internal` 或者 宿主机的内网 IP。

可以参考下这个问题 #36

**Comment by wanngsanchao** [comment]
问题已解决！
出现上述报文的根本原因就是数据库初始化异常导致的，提示其实已经很明显了，是连接不上数据库。可以这么这么操作
1.数据库创建好之后 根据dockerfile 初始化数据库的address port user passwd db
2.关键的步骤对数据库的表项进行初始化，可以不使用下面的两条命令
docker run -it --rm --name my-wizard my-wizard php artisan migrate:install
docker run -it --rm --name my-wizard my-wizard php artisan migrate

直接在应用容器里面执行下面两条命令就可以了：
php artisan migrate:install
php artisan migrate

其实作者已经写过了，只不过关于数据库初始化以及在哪里初始化这些基础的东西，没有提及的详细而已，建议稍微润色下就完美了
![image](https://user-images.githubusercontent.com/66109845/102967556-27e38880-452d-11eb-96e6-c6fb96cab1c5.png)

1.貌似项目没法创建目录呢 这一点需求应该比较多
2.项目的初始化账号密码没有(直接创建账号就可以使用)

**Comment by mylxsw** [comment]
目录创建在这里：右上角用户菜单-系统管理-项目目录管理，目前只支持一级目录，功能比较简单。

项目初始账号密码确实没有，系统规则是第一个注册的用户就是管理员。

**Comment by wanngsanchao** [comment]
> 目录创建在这里：右上角用户菜单-系统管理-项目目录管理，目前只支持一级目录，功能比较简单。
> 
> 项目初始账号密码确实没有，系统规则是第一个注册的用户就是管理员。

目录如果搞成像语雀那样的树形且多级就开心了

**Comment by qiangwushuang** [comment]
问题解决，之前因不知道需要先安装mysql，因此才出现的错误。
但是在安装Mysql后也遇到了一些问题，在此做下记录。
## 未安装Mysql
自行安装Mysql，善用互联网搜索。
## 数据库连接失败
1. 不存在DB_DATABASE中定义的数据库
手动创建名称为wizard的数据库
```shell
mysql -u root -p
mysql> 输入密码
mysql> create database wizard
```
2. 无法使用DB_HOSTNAME中的域名或IP连接
![1](https://user-images.githubusercontent.com/6835840/104084563-20d5ad80-5283-11eb-8033-a1120ab02bd7.png)
![2](https://user-images.githubusercontent.com/6835840/104084565-2632f800-5283-11eb-8fa6-700ea1ebdb97.png)
允许使用localhost或ip登录
```shell
mysql -u root -p 
mysql> 输入Mysql密码
mysql> use mysql;
mysql> update user set host = '%' where user = 'root';
mysql> flush privileges;
```
上面只能使用"%"模式，即允许所有IP，测试使用localhost不行，没搞懂为什么。
3. 身份验证插件导致的问题
![3](https://user-images.githubusercontent.com/6835840/104085509-01db1980-528b-11eb-92f2-67f8b45994a8.png)
```shell
mysql -u root -p 
mysql> 输入Mysql密码
mysql> use mysql;
mysql> ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '你的密码';
mysql> flush privileges;
```
经过以上设置，按照github中的初始化方式应该就可以了。
注意：DB_HOST，DB_DATABASE，DB_USERNAME，DB_PASSWORD要更改为实际的值。
