### ISSUE TITLE
只有登录界面会抛出异常代码，但是功能是ok的。其他界面也都是正常的！

### ISSUE THREAD

**Issue by wanngsanchao** [mylxsw/wizard#128]
大家有碰到这种情况吗？其他界面都是ok的 ，只有登录界面，会有异常代码跑出，功能倒是没啥异常！
![image](https://user-images.githubusercontent.com/66109845/102973195-4d758f80-4537-11eb-826f-65d36b529db7.png)

**Comment by mylxsw** [comment]
这个是个背景图，专门做了这个图，[取消看这里 ](https://github.com/mylxsw/wizard/wiki/%E9%9A%90%E8%97%8F%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E6%9B%B4%E6%8D%A2%E7%99%BB%E5%BD%95%E9%A1%B5%E9%9D%A2%E8%83%8C%E6%99%AF%E5%9B%BE%E7%89%87)
