### ISSUE TITLE
部署提示Base table or view not found: 1146 Table 'wizard.wz_page_tag' doesn't exist 

### ISSUE THREAD

**Issue by qk2012** [mylxsw/wizard#13]
部署提示Base table or view not found: 1146 Table 'wizard.wz_page_tag' doesn't exist ，请问这个表migration里面没看到有啊？

**Comment by mylxsw** [comment]
能详细说一下是什么情况下出现的这个错误吗？或者截个图看，`wz_page_tag` 表的 migration 在 **2018_05_10_105629_create_page_tag_table.php** 中

**Comment by qk2012** [comment]
> 能详细说一下是什么情况下出现的这个错误吗？或者截个图看，`wz_page_tag` 表的 migration 在 **2018_05_10_105629_create_page_tag_table.php** 中

应该是migration执行报错导致的，没有完整的执行，下面是报错的截图
![image](https://user-images.githubusercontent.com/36978582/56027759-413ca500-5d49-11e9-97a6-8e14bd13dff0.png)，这个错误我看你已经做了处理了，不清楚为什么还是会报错，环境原因？我暂时把唯一索引修改为普通索引，目前系统可以正常运行了。感谢。
