### ISSUE TITLE
希望可以添加对mariadb的支持

### ISSUE THREAD

**Issue by DUWENINK** [mylxsw/wizard#16]
Dockerfile配置信息
![o_1dabpcgah1n7nb7vfpbs901u2va.jpg](http://cdn.duwen.ink/o_1dabpcgah1n7nb7vfpbs901u2va.jpg)
运行`docker run -it --rm --name my-wizard my-wizard php artisan migrate:install`
报错
![o_1dabpfkdbnhlt8bgvj5i5kcna.jpg](http://cdn.duwen.ink/o_1dabpfkdbnhlt8bgvj5i5kcna.jpg)
后改mysql认证方式问题仍未解决，怀疑是musql装在docker中的问题

**Comment by mylxsw** [comment]
支持Mariadb的，可能是因为你用的Mariadb版本比较新，对应的MySQL版本在8.0之后也可能会有问题（默认认证方式修改为了`caching_sha2_password`），解决办法可以试试下面这样

连接到数据库，修改一下密码的认证方式为 `mysql_native_password`：

    ALTER USER 'USERNAME'@'HOSTNAME' IDENTIFIED WITH mysql_native_password BY 'PASSWORD';

> 参考 [Caching SHA-2 Pluggable Authentication](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html)

**Comment by DUWENINK** [comment]
> 支持Mariadb的，可能是因为你用的Mariadb版本比较新，对应的MySQL版本在8.0之后也可能会有问题（默认认证方式修改为了`caching_sha2_password`），解决办法可以试试下面这样
> 
> 连接到数据库，修改一下密码的认证方式为 `mysql_native_password`：
> 
> ```
> ALTER USER 'USERNAME'@'HOSTNAME' IDENTIFIED WITH mysql_native_password BY 'PASSWORD';
> ```
> 
> > 参考 [Caching SHA-2 Pluggable Authentication](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html)

重新更换了数据库 运行` docker run -it --rm --name my-wizard my-wizard php artisan migrate:install `脚本之后提示 ![o_1dag2ctp4n8uusj19lva4sj23a.jpg](http://cdn.duwen.ink/o_1dag2ctp4n8uusj19lva4sj23a.jpg)
返回信息`select * from information_schema.tables where table_schema = wizard and table_name =
   migrations`查询条件缺少引号 改成`select * from information_schema.tables where table_schema = 'wizard' and table_name =
   'migrations'`之后在数据库内可以查询到数据，希望作者大大协助修改异常

**Comment by mylxsw** [comment]
看起来是数据库服务器地址有问题，你改成IP地址试试，还有就是启动容器后，再本地执行一下这个命令

    docker exec -it my-wizard php artisan config:clear

这条命令会清空my-wizard容器中的配置缓存。

**Comment by DUWENINK** [comment]
已经被劝退

**Comment by DUWENINK** [comment]
问题并没有被解决。。。。。。。当我运行`docker run -it --rm --name my-wizard my-wizard php artisan migrate`的时候 出现了如图所示的报错，![o_1dancnhed1dl614cn154f1q2rrea.jpg](http://cdn.duwen.ink/o_1dancnhed1dl614cn154f1q2rrea.jpg)

**Comment by mylxsw** [comment]
我试了最新的 Mariadb 10.4 是OK的，可能是因为 `sql_mode` 不同的问题。我修改了一下代码，为 created_at 字段添加了默认值。你再更新下镜像试试应该就可以了

    docker pull mylxsw/wizard:latest

Docker Hub 上的页面为 https://hub.docker.com/r/mylxsw/wizard

**Comment by DUWENINK** [comment]
重新拉取最新版的 配置了自己的链接字符串 运行  到`docker run -it --rm --name my-wizard my-wizard php artisan migrate`报错, 数据库版本(MYSQL5.6其实是从最新版换到了5.6)如图
![o_1daqfprp0kdlr0c1ej8ouu1mmpa.jpg](http://cdn.duwen.ink/o_1daqfprp0kdlr0c1ej8ouu1mmpa.jpg)

**Comment by DUWENINK** [comment]
`SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: create table `wz_operation_logs` (`id` int unsigned not
  null auto_increment primary key, `user_id` int unsigned null comment '操作用户ID', `message` varchar(255) null comment '日志消息内容', `context` text null co
  mment '记录日志时候的上下文信息', `created_at` timestamp not null comment '创建时间') default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = ARC
  HIVE)
`

**Comment by mylxsw** [comment]
应该是更新docker镜像出了问题，从输出的SQL看并不是最新的，最新的输出的这个表的sql是这样子的

    create table `wz_operation_logs` (
        `id` int unsigned not null auto_increment primary key, 
        `user_id` int unsigned null comment '操作用户ID', 
        `message` varchar(191) null comment '日志消息内容', 
        `context` text null comment '记录日志时候的上下文信息', 
        `created_at` timestamp default CURRENT_TIMESTAMP not null comment '创建时间'
    ) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = ARCHIVE

其中变化的部分是 

    `created_at` timestamp default CURRENT_TIMESTAMP not null comment '创建时间'

我重新打了个包，你再更新下试试，为了避免出现不是最新的问题，建议你直接指定tag 1.0.3，使用镜像的时候这样

	FROM mylxsw/wizard:1.0.3

	# 数据库连接配置
	# 这里可以根据需要添加其它的Env配置，可用选项参考项目的.env.example文件
	ENV DB_CONNECTION=mysql
	ENV DB_HOST=host.docker.internal
	ENV DB_PORT=3306
	ENV DB_DATABASE=wizard_2
	ENV DB_USERNAME=wizard
	ENV DB_PASSWORD=wizard
	ENV WIZARD_NEED_ACTIVATE=false

	# 文件上传存储目录
	VOLUME /webroot/storage/app/public

	RUN php artisan config:cache
