### ISSUE TITLE
邮件功能开通了嘛？

### ISSUE THREAD

**Issue by wuhongyuwhy** [mylxsw/wizard#171]
请问邮件功能 能否使用啊，我测试找回密码报错。
Cannot send message without a sender address。
在哪里配置邮件呢

**Comment by mylxsw** [comment]
参考这里 [系统定制配置](https://github.com/mylxsw/wizard/wiki/%E7%B3%BB%E7%BB%9F%E5%AE%9A%E5%88%B6%E9%85%8D%E7%BD%AE#%E9%82%AE%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE)

**Comment by ZTFGU** [comment]
我按照配置填写的，它报错了，报错如下：
stream_socket_enable_crypto():SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate verify failed.
我查了一下午的资料，没搞定，我填写的邮件配置如下：（应该是没有问题的）
MAIL_HOST=192.168.95.13
MAIL_PORT=587
MAIL_USERNAME=wx-whatsup@xxxx.com
MAIL_PASSWORD=xxxxxx
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDRESS=wx-whatsup@xxxxx.com
MAIL_FROM_NAME="WhatsUp-ReSet-Password"
MAIL_DRIVER=smtp
大佬，能麻烦你抽空看看嘛？不胜感激！！！抱拳！
已收藏，已start

**Comment by mylxsw** [comment]
看起来是 SSL 连接问题，你的 HOST 是 192.168.95.13，确定下邮箱的 SMTP 是支持 TLS 加密的，如果不是，则可以试试把加密去掉 `MAIL_ENCRYPTION=null`

**Comment by ZTFGU** [comment]
是的，是支持TLS_V1.2的
是在公司内网的邮件服务器上，IP都对，我用openssl也测试过了，支持TLS。
楼主你说的这几种组合我都试过了，不行。
我在猜想，是不是服务器端的证书无法验证客户端的证书，有点蒙了

**Comment by mylxsw** [comment]
DeepSeek 深度思考的结果，我觉得你可以试试，还是有些参考性的。

这个错误通常与 SSL 证书验证失败有关。以下是可能的原因和解决方案：

### 1. 证书验证问题（最常见）
- **原因**：服务器使用自签名证书或证书链不完整
- **解决方案**：
```env
# 临时关闭证书验证（测试用，生产环境不推荐）
MAIL_VERIFY_PEER=false
```
注意：如果此方法生效，说明确实是证书问题，但长期解决方案应该是正确配置证书

### 2. 主机名不匹配
- **原因**：服务器证书的 Common Name 或 Subject Alternative Name 与 MAIL_HOST 不匹配
- **检查**：确保 MAIL_HOST 使用与证书匹配的域名而非 IP 地址
```env
# 尝试改用域名（如果证书是颁发给域名的）
MAIL_HOST=mail.yourdomain.com
```

### 3. CA 证书包缺失
- **原因**：PHP 找不到根证书包进行验证
- **解决方案**：
```env
# 指定 CA 证书路径
MAIL_STREAM_OPTIONS='{"ssl": {"verify_peer": true, "verify_peer_name": true, "cafile": "/etc/ssl/certs/ca-certificates.crt"}}'
```
（路径根据系统不同可能需要调整，Ubuntu 通常使用上述路径）

### 4. 混合使用 TLS/SSL
- **检查端口和加密组合**：
```env
# 正确组合方案：
# 方案1 (推荐)
MAIL_PORT=587
MAIL_ENCRYPTION=tls

# 方案2
MAIL_PORT=465
MAIL_ENCRYPTION=ssl
```

### 5. 服务器配置问题
- **检查邮件服务器**：
1. 确认服务器支持 STARTTLS
2. 检查服务器证书是否有效：
```bash
openssl s_client -connect 192.168.95.13:587 -starttls smtp
```
3. 检查证书是否包含完整链

### 6. PHP 版本兼容性
- 确保 OpenSSL 扩展已启用且版本 >= 1.0.1

### 建议排查步骤：
1. 先用 `telnet 192.168.95.13 587` 测试基础连接
2. 执行 `openssl s_client` 命令检查证书详情
3. 临时关闭验证确认是否证书问题
4. 检查服务器时间是否同步（证书有效期验证依赖时间同步）

根据经验，这类问题 80% 的情况是：自签名证书未配置信任 或 使用 IP 地址访问但证书是颁发给域名的。建议优先检查证书有效性。

如果需要进一步帮助，可以提供以下信息：
1. `openssl s_client` 命令输出（隐藏敏感信息）
2. PHP 版本
3. 服务器操作系统信息

**Comment by ZTFGU** [comment]
我都试了，后面根据报错，我发现是因为服务器支持NTLM，请问大佬，你的代码有写NTLM的相关部分代码吗
