### ISSUE TITLE
无导出功能，用不了

### ISSUE THREAD

**Issue by benfeng** [mylxsw/wizard#18]
无导出功能，用不了

**Comment by benfeng** [comment]
就卡在这个功能上面，有就完美了

**Comment by mylxsw** [comment]
嗯，这个很快就有了，计划近期添加上去，之前加了，不过导出pdf功能需要本地环境配置，比较麻烦，所以就屏蔽掉了

**Comment by mylxsw** [comment]
文件导出功能已经添加了，目前还不是很完善

- 单个 markdown 文件导出为 PDF/ Markdown
- 单个 swagger 文件导出为 JSON/YAML 文档
- 批量导出 Markdown 为一个 PDF 文档，目前只支持 Markdown
- 批量导出 项目下的文档为 压缩包，所有格式的文档打包下载

**Comment by benfeng** [comment]
太好了，试试

**Comment by benfeng** [comment]
我目录没写任何内容，占了一整页空白，
不能定义仅为目录

**Comment by benfeng** [comment]
目录顺序调整 不了

**Comment by lvtu0316** [comment]
> 文件导出功能已经添加了，目前还不是很完善
> 
> * 单个 markdown 文件导出为 PDF/ Markdown
> * 单个 swagger 文件导出为 JSON/YAML 文档
> * 批量导出 Markdown 为一个 PDF 文档，目前只支持 Markdown
> * 批量导出 项目下的文档为 压缩包，所有格式的文档打包下载

导出 Pdf 需要怎样的配置，导出报错！
`Call to undefined function Mpdf\Writer\gzcompress()`
Markdown 导出没问题。

**Comment by mylxsw** [comment]
php需要支持zlib扩展，参考下 [如何安装zlib扩展](https://www.baidu.com/s?wd=php%20%E5%AE%89%E8%A3%85%20zlib%20%E6%89%A9%E5%B1%95)

**Comment by lvtu0316** [comment]
> php需要支持zlib扩展，参考下 [如何安装zlib扩展](https://www.baidu.com/s?wd=php%20%E5%AE%89%E8%A3%85%20zlib%20%E6%89%A9%E5%B1%95)

![image](https://user-images.githubusercontent.com/29847918/63013135-237d7900-bebe-11e9-980e-a37efa976b2b.png)
安装了 zlib 扩展，但是还是这个报错，
`Call to undefined function Mpdf\Writer\gzcompress()`
我本地的PHP环境是可以使用导出pdf的，但是我这两个环境扩展差的有点多，所以这个pdf支持具体需要哪些扩展呢？还麻烦版主最好在文档中说明下。
这是我线上PHP扩展：
`[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib
`

**Comment by mylxsw** [comment]
按理说pdf支持需要这几个扩展：`mbstring`，`gd`，`zlib`，`xml`，参见 [MPDF](https://github.com/mpdf/mpdf) 的文档。

我这边所有的功能都是OK的，扩展有这些

```
[root@wiki ~]# php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

你可以参考一下。

**Comment by lvtu0316** [comment]
对比之后，我又安装了以下三个扩展：

extension=zip.so
extension=ldap.so
extension=opcache.so

刷新页面仍然报错，我重启了php-fpm ，导出pdf 可以了，所以我感觉还是 zlib 的问题，跟这三个扩展应该没关系。安装了 zlib 之后，虽然 php -m 可以查看扩展安装成功，但是仍然需要重启PHP。

**Comment by mylxsw** [comment]
嗯，php 安装任何扩展之后都需要重启 fpm 才能生效的

**Comment by benfeng** [comment]
发现一个问题，导出PDF时顺序与显示顺序不一致
我开始写了两个目录（A,B），后面又加了一个目录(C)，我把顺序改成（C, A,B)  ，但导出顺序还是 A,B,C
希望导出是 C,A,B,与显示顺序一致

**Comment by mylxsw** [comment]
我试了下，先创建三个目录 A/B/C，然后调整排序为 C/A/B，导出PDF，是按照排序后的顺序导出的，没有复现该问题，能否详细说下你的具体操作步骤呢

**Comment by benfeng** [comment]
> 我试了下，先创建三个目录 A/B/C，然后调整排序为 C/A/B，导出PDF，是按照排序后的顺序导出的，没有复现该问题，能否详细说下你的具体操作步骤呢

我知道了，一般导出是没有问题，在这情况下有问题
假设项目目录三层，在编辑模式下进入项目，点导出，再选某一级目录，就发现目录顺序还是没变
