### ISSUE TITLE
账号创建后的出现的“加载中”和“数加载错误，请稍后重试”

### ISSUE THREAD

**Issue by Devnull6** [mylxsw/wizard#19]
![image](https://user-images.githubusercontent.com/28561071/57820745-947a9b00-77c0-11e9-899f-29f732ebd6f1.png)

**Comment by Devnull6** [comment]
账号管理问题，目前只能通过注册方式添加用户，不能在用户管理中添加本地账号，并且账号只能是邮箱形式，不支持用户名方式登录
![image](https://user-images.githubusercontent.com/28561071/57821494-516df700-77c3-11e9-9066-d8a6f6731023.png)

**Comment by mylxsw** [comment]
数据加载错误的问题待我仔细查查，帐号分配的问题已经加入开发计划
