### ISSUE TITLE
开发计划之文档分享，递归分享目录及子目录，文档，还是很有必要的

### ISSUE THREAD

**Issue by wangscsgit** [mylxsw/wizard#202]
目录不能分享，只能分享具体页面，如何做到分享层级目录？

**Comment by mylxsw** [comment]
没理解这里说的目录是什么，在 wizard 中目录也是文档，是可以直接分享的，你的意思是一次性分享一个页面以及它所有的子页面？

**Comment by wangscsgit** [comment]
感谢回复，是这个意思，比如分享目录1，是希望能分享目录1和它所有的子目录，页面 。

——目录1
————子目录1
——————文档页面1
——————文档页面2
————文档页面

**Comment by wangscsgit** [comment]
有时候需要分享多层的目录给别人，现在分享目录，就是空白页面，只能一个个子目录页面单独分享，很不方便
