### ISSUE TITLE
Docker部署时遇到SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by mobguang** [mylxsw/wizard#214]
重现步骤：
1. 执行下列命令：
docker run -it --rm --name wizard \
    -e DB_HOST=host.docker.internal \
    -e DB_PORT=3306  \
    -e DB_DATABASE=wizard  \
    -e DB_USERNAME=wizard  \
    -e DB_PASSWORD=wizard  \
    mylxsw/wizard

2. 在docker环境中执行：php artisan migrate:install

遇到下列错误：
**SQLSTATE[HY000] [2002] Connection refused (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary
  key, `migration` varchar(191) not null, `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')**

哪位大神可以帮忙看一下，可以如何解决，不胜感激！

**Comment by mylxsw** [comment]
连不上数据库，检查下你宿主机上的数据库是否启动了，账号密码权限是否已经分配

**Comment by mobguang** [comment]
Hi @mylxsw ,

感谢回复。我后来尝试的步骤如下：

1. 我在主机上通过docker启动了mysql，并且执行了如下mysql的初始化脚本：
create database wizard default character set utf8mb4 collate utf8mb4_bin ;
create user 'wizard'@'%' identified by 'wizard' ;
grant all privileges on wizard.* to 'wizard'@'%' ;
flush privileges ;

2. 然后在本机执行了如下脚本：
docker run -d --name wizard \
    -e DB_HOST=10.8.18.87 \
    -e DB_PORT=3306  \
    -e DB_DATABASE=wizard  \
    -e DB_USERNAME=wizard  \
    -e DB_PASSWORD=wizard  \
    -p 8080:80 \
    -v /Volumes/M2SSD/Space/GuangResourcesPool/Guang_workspace/Inceptio/workspace/wizard/content:/webroot/storage/app/public   \
    mylxsw/wizard

3. 执行docker exec -it wizard /bin/bash，进入docker；
4. 执行php artisan migrate:install，遇到如下error：

**SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: create table `migrations` (`id`
   int unsigned not null auto_increment primary key, `migration` varchar(191) not null, `batch` int not null) default character
   set utf8mb4 collate 'utf8mb4_unicode_ci')**

请问是哪一步有问题吗，感谢指导！

**Comment by mylxsw** [comment]
这是用的 mysql8 吧，这样，修改下用户信息

```bash
alter user 'wizard'@'%' identified with mysql_native_password by 'wizard';
```

**Comment by mobguang** [comment]
Hi @mylxsw ,

谢谢，可以启动了。
