### ISSUE TITLE
php 7.4.33 下 composer 安装时就出错

### ISSUE THREAD

**Issue by peyoot** [mylxsw/wizard#225]
php 7.4.33 , composer 2.5.8
下载源码后，用composer install --prefer-dist --ignore-platform-reqs 出错：
![image](https://github.com/mylxsw/wizard/assets/2165697/e215f1d9-da3c-4ca3-a454-9528624ecc10)

**Comment by peyoot** [comment]
最终用官方容器的方式进入，安装好后打包webroot出来，放在自己的web环境，修改一下public/storage链接，可正常使用。
希望国产开源越做越好！
其实软件不挑环境，主要是composer安装过程容易出问题，索性就不要用自己环境的composer，一切就好解决了。

**Comment by Amos1st** [comment]
再运行一下 `composer update` 就可以了，可能是 `composer.lock` 没有放进版本管理吧，`composer install` 时候的包版本不合适
