### ISSUE TITLE
创建的模板只适用于 Swagger 文档吗？Markdown 文档如何使用已保存文档

### ISSUE THREAD

**Issue by lvtu0316** [mylxsw/wizard#24]
创建的模板只适用于 Swagger 文档吗？Markdown 文档如何使用已保存文档，如果不能使用，另存为模板也就没什么作用了吧？

**Comment by mylxsw** [comment]
选择模板和json转表格按钮已经替换为文字了，更容易识别一些

![img](http://ww3.sinaimg.cn/large/006tNc79ly1g5zcoee1wej30bd02y3yy.jpg)
