### ISSUE TITLE
新建文档总是提示“发现有尚未保存的内容，是否继续编辑”

### ISSUE THREAD

**Issue by lvtu0316** [mylxsw/wizard#26]
复制本地内容，新建文档完后，再次新建MD文档，总是弹窗提示，“发现您有尚未保存的内容，是否继续编辑？ ”   
这是检查的剪切板内容故意做的这种效果？还是bug呢？

**Comment by mylxsw** [comment]
多谢提醒，是个bug，已经修复，更新下代码就好了
