### ISSUE TITLE
不能上传图片及文档类型

### ISSUE THREAD

**Issue by wellswong1990** [mylxsw/wizard#28]
1、docker 容器化后挂载/webroot/storage/app/public 后不能上传图片及文档类型
2、上传大小超过2M没办法上传请问在哪里设置？

**Comment by wellswong1990** [comment]
上传的图片限制成了2M，能更大点吗？

**Comment by mylxsw** [comment]
已经调整为 **100M**，Docker 镜像的话使用最新的 1.0.5

    FROM mylxsw/wizard:1.0.5

如果需要更大的文件上传，Docker 镜像的话，应该可以通过添加下面命令重新打包解决，指定更大的大小限制

    RUN echo "upload_max_filesize = 100M\npost_max_size = 0" > "$PHP_INI_DIR/conf.d/upload-limit.ini"

如果是自己装的 PHP 环境运行，参考 [FAQ](https://github.com/mylxsw/wizard#faq) 问题4。

**Comment by wellswong1990** [comment]
> 已经调整为 **100M**，Docker 镜像的话使用最新的 1.0.5
> 
> ```
> FROM mylxsw/wizard:1.0.5
> ```
> 
> 如果需要更大的文件上传，Docker 镜像的话，应该可以通过添加下面命令重新打包解决，指定更大的大小限制
> 
> ```
> RUN echo "upload_max_filesize = 100M\npost_max_size = 0" > "$PHP_INI_DIR/conf.d/upload-limit.ini"
> ```
> 
> 如果是自己装的 PHP 环境运行，参考 [FAQ](https://github.com/mylxsw/wizard#faq) 问题4。

那docker 容器化后挂载/webroot/storage/app/public 后不能上传图片及文档类型怎么解决呢？

**Comment by mylxsw** [comment]
对于这个问题 “那docker 容器化后挂载/webroot/storage/app/public 后不能上传图片及文档类型怎么解决呢？”，能否详细描述一下呢

- 无法上传图片还是所有的文件都无法上传呢，报错了吗，还是返回什么信息？
- 挂载 `/webroot/storage/app/public`，你的操作步骤是什么

**Comment by wellswong1990** [comment]
> 对于这个问题 “那docker 容器化后挂载/webroot/storage/app/public 后不能上传图片及文档类型怎么解决呢？”，能否详细描述一下呢
> 
> * 无法上传图片还是所有的文件都无法上传呢，报错了吗，还是返回什么信息？
> * 挂载 `/webroot/storage/app/public`，你的操作步骤是什么

随便挂载 不一定要挂载到 /webroot/storage/app/public目录
只要用了挂载的东西，上传文件及上传图片就没办法用
![image](https://user-images.githubusercontent.com/20511068/63820967-d00b3080-c97d-11e9-9851-0ae2e3eefbea.png)
