### ISSUE TITLE
前端增加版本号显示

### ISSUE THREAD

**Issue by wellswong1990** [mylxsw/wizard#30]
建议在前端增加版本号显示或者更新的内容，
可以考虑在右上角用户名下拉里增加

**Comment by mylxsw** [comment]
感谢建议，已经添加，不过为了避免干扰用户，放到页面底部了，详见 [1.0.7](https://github.com/mylxsw/wizard/releases/tag/1.0.7)

**Comment by wellswong1990** [comment]
> 感谢建议，已经添加，不过为了避免干扰用户，放到页面底部了，详见 [1.0.7](https://github.com/mylxsw/wizard/releases/tag/1.0.7)

好的感谢
