### ISSUE TITLE
docker-compose.yml文件部署失败, php部署报错

### ISSUE THREAD

**Issue by lee362** [mylxsw/wizard#33]
部署环境: Ubuntu 16.04
docker version: 19.03.3
docker-compose version: 1.24.1, build 4667896b

php_1      | Do not run Composer as root/super user! See https://getcomposer.org/root for details
php_1      | Loading composer repositories with package information
php_1      | 
php_1      |                                                                                                                                                                                     
php_1      |   [Composer\Downloader\TransportException]                                                                                                                                          
php_1      |   The "https://packagist.laravel-china.org/packages.json" file could not be downloaded: Peer certificate CN=`*.phphub.org' did not match expected CN=`packagist.laravel-china.org'  
php_1      |   Failed to enable crypto                                                                                                                                                           
php_1      |   failed to open stream: operation failed                                                                                                                                           
php_1      |                                                                                                                                                                                     
php_1      | 
php_1      | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
php_1      | 
php_1      | 
php_1      | Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17
php_1      | 
php_1      | Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17
php_1      | 
php_1      | Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17
php_1      | 
php_1      | Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17
php-fpm_1  | [16-Oct-2019 08:17:44] NOTICE: fpm is running, pid 1
php-fpm_1  | [16-Oct-2019 08:17:44] NOTICE: ready to handle connections
wizard_php_1 exited with code 255

**Comment by mylxsw** [comment]
这个是因为没有安装依赖包，你可以手动下载vender，解压缩到项目的根目录下就可以了

    https://github.com/mylxsw/wizard/releases/download/1.0.4/vendor.tar.gz
