### ISSUE TITLE
docker容器部署无法挂载本地路径

### ISSUE THREAD

**Issue by Destiny99371** [mylxsw/wizard#35]
![image](https://user-images.githubusercontent.com/49816155/67826836-df873100-fb08-11e9-9ef2-ef8ffa505c45.png)
我把图片和文档的路径通过-v 映射到本地，启动后上传图片之类的都没有报错但是就是没办法上传

**Comment by Destiny99371** [comment]
请问是启动做了什么初始化的操作，导致挂载本地不能使用吗

**Comment by Destiny99371** [comment]
![image](https://user-images.githubusercontent.com/49816155/67826945-34c34280-fb09-11e9-982e-d363ef26cf61.png)

**Comment by mylxsw** [comment]
你的 Dockerfile 发出来看看呢

**Comment by Destiny99371** [comment]
FROM mylxsw/wizard

# 数据库连接配置
ENV DB_CONNECTION=mysql
ENV DB_HOST=192.9.102.129
ENV DB_PORT=3306
ENV DB_DATABASE=wizard
ENV DB_USERNAME=wizard
ENV DB_PASSWORD=nB5Nt6t$
ENV WIZARD_NEED_ACTIVATE=false
# 文件上传存储目录
VOLUME /webroot/storage/app/public

RUN php artisan config:cache

**Comment by Destiny99371** [comment]
这个只是生成镜像的吧！ 我是启动镜像的时候用挂载

**Comment by Destiny99371** [comment]
刚刚试了下只能挂载一个根目录文件，不能挂载到根目录里面去
失败
![image](https://user-images.githubusercontent.com/49816155/67927333-4bde5f00-fbf3-11e9-9cda-6568d320915c.png)

成功
![image](https://user-images.githubusercontent.com/49816155/67927341-526cd680-fbf3-11e9-91a8-5498f92b92ba.png)

**Comment by Destiny99371** [comment]
这边没办法解决吗

**Comment by mylxsw** [comment]
我试过了，这样是可以的

    docker run --rm --name my-wizard -p 8080:80 -v /tmp:/webroot/storage/app/public  my-wizard

如果你用的是桌面版的 Docker 的话，注意共享的目录必须是在 Docker 中配置允许共享才可以正常挂载的，如 mac 下

![img](https://ssl.aicode.cc/2019-11-13-15736271259532.jpg)

上面我共享的是 /tmp 目录，在 Docker 中是配置其允许文件共享的。

**Comment by fnmsd** [comment]
宿主机上的文件夹得给777权限。
