### ISSUE TITLE
通过 Docker 安装时数据库初始化错误

### ISSUE THREAD

**Issue by niezixu** [mylxsw/wizard#36]
![image](https://user-images.githubusercontent.com/20469846/68571525-29bfc900-049e-11ea-8ad8-8aefc04816dd.png)
想问下，使用宿主机的mysql出现如上这个错误是什么原因?

**Comment by mylxsw** [comment]
这个错误是说无法识别 `host.docker.internal` 这个域名对应的 MySQL 服务，检查下这两点

- 宿主机的 MySQL 是否已经启动，账号密码创建完成
- Docker版本

**Comment by mylxsw** [comment]
参考一下这里 [Networking features in Docker Desktop for Mac](https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds)。

> The host has a changing IP address (or none if you have no network access). From 18.03 onwards our recommendation is to connect to the special DNS name host.docker.internal, which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Mac.

> The gateway is also reachable as gateway.docker.internal

Docker 版本要大于 18.03 。

**Comment by niezixu** [comment]
这个问题我处理了，好像host.docker.internal只支持windows和mac系统吧，Ubuntu不支持，所以我换成Ip后就可以了

**Comment by qiaobaochen** [comment]
你好，host.docker.internal 改成自己的ip（192.168.1.124或者是docker0 172.17.0.1）为什么还会取访问172.17.0.2？很奇怪
![image](https://user-images.githubusercontent.com/22009264/69145032-a8a0ab80-0b07-11ea-97c3-e88a24724f7a.png)

**Comment by niezixu** [comment]
你这个错误是表示你没有权限连接你的数据库吧？看下是否开启了远程访问连接
