### ISSUE TITLE
导出的PDF或者MarkDown文件中的图片无法显示，只是个链接！

### ISSUE THREAD

**Issue by niezixu** [mylxsw/wizard#37]
如图：
![image](https://user-images.githubusercontent.com/20469846/68662620-2731a200-0578-11ea-8d4c-4046e8a73995.png)
**除此问题之后搜索功能也不可用，搜索没有结果显示；**

=========================================================
通过访问在线体验地址 http://wizard.aicode.cc/ 发现线上版本这两个问题是正常的，我是通过DockerFile方式安装的，请问Docker Hub中的项目是否是最新的？

**Comment by mylxsw** [comment]
OK，已经复现该问题，预计今天就能解决，只有通过 Docker 部署的会有这个问题

**Comment by niezixu** [comment]
搜索功能这个问题是不是也存在问题？搜索没有结果

> OK，已经复现该问题，预计今天就能解决，只有通过Docker部署的会有这个问题

**Comment by mylxsw** [comment]
已经解决了，更新最新的镜像或者代码就可以了，导出Markdown的问题需要在 Dockerfile 添加环境变量

    ENV APP_URL=http://localhost:8080

搜索没结果的问题最好单独提一个新的问题，描述下怎么复现

**Comment by niezixu** [comment]
Ok，我更新后试试！通过Docker更新的话，在Dockerfile中添加这个变量，我是需要将之前部署的删掉然后重新部署吗？
搜索没有结果的这个问题是必现的，我通过Docker部署之后就使用不了，搜索结果是空白的；

**Comment by mylxsw** [comment]
对的，需要将之前的部署删除，拉取最新的镜像，重新 build，再启动，搜索问题我这复现不了，新开个问题吧，比如什么关键字搜索的啊都说一下，我也好诊断啥问题😁

![](https://ssl.aicode.cc/2019-11-13-15736272735052.jpg)

**Comment by niezixu** [comment]
这样重新部署那之前的数据库是不是也清空了？这样以后你这边要迭代版本，岂不是很不方便

**Comment by mylxsw** [comment]
数据库是独立部署的，不会受到这个的影响，图片的话，用docker要挂载一个本地目录上去，这个超过这个项目的范畴了，所以就没有写这一部分文档，比如这样

    docker run --rm --name my-wizard -p 8080:80 -v /tmp:/webroot/storage/app/public  my-wizard

这里把本地的 /tmp 目录映射到容器中的 /webroot/storage/app/public 目录，这样不管怎么重启，部署，只要本地文件没有被删除，图片附件等都还是在的。

**Comment by niezixu** [comment]
ok，懂你的意思了。Docker删除重新部署后不需要删掉之前的数据库和执行数据库初始化步骤对吧，直接运行docker就行，然后图片内容是存储在映射到本地的路径下删除Docker不影响哈

**Comment by mylxsw** [comment]
对的

**Comment by niezixu** [comment]
> -v /tmp:/webroot/storage/app/public

通过这种方式挂在本地目录是出现如下错误：
![image](https://user-images.githubusercontent.com/20469846/68766624-2d984a80-065a-11ea-90c3-3e20dc08b337.png)

**Comment by niezixu** [comment]
> > -v /tmp:/webroot/storage/app/public
> 
> 通过这种方式挂在本地目录是出现如下错误：
> ![image](https://user-images.githubusercontent.com/20469846/68766624-2d984a80-065a-11ea-90c3-3e20dc08b337.png)
> 
> 而如果直接通过运行挂载的话就没法进行图片上传了，此问题如：[#28 (comment)](https://github.com/mylxsw/wizard/issues/28#issuecomment-525560519)

此问题是由于挂在的文件目录权限问题，执行sudo chmod 777 filepath就可以了
