### ISSUE TITLE
通过Docker部署后搜索功能不可用！

### ISSUE THREAD

**Issue by niezixu** [mylxsw/wizard#38]
这是搜索前输入：
![image](https://user-images.githubusercontent.com/20469846/68739687-61f11400-0624-11ea-887f-56ba4940531e.png)
这是搜索后结果：
![image](https://user-images.githubusercontent.com/20469846/68739811-b85e5280-0624-11ea-86b2-76655aa13402.png)

这个问题我在你提供的在线预览项目中没有发现，但在我本地部署就搜索不了！

**Comment by mylxsw** [comment]
你要搜索的是文档标题吗，这个搜素现在只支持搜索文档标题的，目前不支持搜索目录或者项目名称😂

**Comment by niezixu** [comment]
![image](https://user-images.githubusercontent.com/20469846/68740447-0aec3e80-0626-11ea-8cc3-eacedc219cd0.png)
目前只支持搜索文档标题？如上图中的“我的测试”吗？文档的内容支持搜索吗？
![image](https://user-images.githubusercontent.com/20469846/68740531-3ec76400-0626-11ea-9ba7-640d4d667802.png)

**Comment by mylxsw** [comment]
对，目前只支持标题的模糊搜索，比如上面这个，只能“我的测试”，其实就是简单的  like 查询，比如搜索 “我的”，“测试” 都是可以的。

文档多了之后，文档内容搜索对性能影响会比较大，所以没有支持。

后面可能会考虑增加全文检索等高级搜索方法，但是可能会增加部署的复杂度，所以目前版本没有该功能。

**Comment by niezixu** [comment]
好的，明白，多谢解答！
