### ISSUE TITLE
点击上传的Markdown文件附件附件预览时中文显示乱码

### ISSUE THREAD

**Issue by niezixu** [mylxsw/wizard#39]
V1.0.9版本：
![image](https://user-images.githubusercontent.com/20469846/68823536-04fe6800-06cf-11ea-939a-edf5e244d858.png)

在你提供的线上预览版本中是V1.0.8版本，点击附件时是直接下载文件：
![image](https://user-images.githubusercontent.com/20469846/68823683-79390b80-06cf-11ea-985d-b405f08cb5d0.png)

**Comment by mylxsw** [comment]
Wizard 本身并不提供线上预览上传的附件的，正确的行为应该是点击直接下载文件，线上预览版本那个是用的 Nginx 部署，而 Docker 容器中则是用的 Apache，两者默认的文件下载确实有些差异，我更新了项目下的 .htacess 文件，让其能够直接下载文件。

更新 Docker 镜像到最新的 1.0.10 或者 latest 就可以了。
