### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by seeidea** [mylxsw/wizard#40]
php artisan migrate:install

In Connection.php line 664:
                                                                                                                                                  
  SQLSTATE[HY000] [2002] No such file or directory (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary key, `migr  
  ation` varchar(191) not null, `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')                                 
                                                                                                                                                  

In PDOConnection.php line 31:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In PDOConnection.php line 27:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by mylxsw** [comment]
修改数据库连接地址，账号密码，并确保可以正常访问就可以了

**Comment by seeidea** [comment]
DB_CONNECTION=mysql   这项不用变更
DB_HOST=localhost    这个本机用localhost
DB_PORT=3306
DB_DATABASE=xxxx  
DB_USERNAME=xxxxx
DB_PASSWORD=xxxxxx

这种填写格式应该没有问题吧， 也是按照样例修改的

**Comment by seeidea** [comment]
已经反复测试了， 在本机上使用  mysql -hlocalhost -u用户名 -P端口 -p密码   是可以连接的

php artisan migrate:install 该命令有没有debug模式呀？

**Comment by mylxsw** [comment]
试试把 DB_HOST 改成 127.0.0.1，可以参考下这个

https://www.cnblogs.com/gyrgyr/p/10449618.html

**Comment by seeidea** [comment]
好了， thanks
