### ISSUE TITLE
关于用户权限的建议！

### ISSUE THREAD

**Issue by niezixu** [mylxsw/wizard#41]
目前针对用户组分配了修改权限，但是没有控制是否可读权限，建议可以加上针对用户组分配查看项目的功能，最好和修改分开设置；
![image](https://user-images.githubusercontent.com/20469846/69115597-14f9bb80-0ac4-11ea-8440-8047f9158fda.png)

**Comment by mylxsw** [comment]
感谢建议，为用户组分配权限时，不勾选“允许修改”，就可以直接添加只读权限了
