### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by qiaobaochen** [mylxsw/wizard#42]
php_1      | Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17

找不到这个文件

**Comment by qiaobaochen** [comment]
php_1      |
php_1      |
php_1      |   [Composer\Downloader\TransportException]
php_1      |   The "https://packagist.laravel-china.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
php_1      |   error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
php_1      |   Failed to enable crypto
db_1       | 2019-11-19T05:57:28.081435Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1       | 2019-11-19T05:57:28.081453Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1       | 2019-11-19T05:57:28.081457Z 0 [Note] InnoDB: Uses event mutexes
db_1       | 2019-11-19T05:57:28.081460Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1       | 2019-11-19T05:57:28.081463Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1       | 2019-11-19T05:57:28.081465Z 0 [Note] InnoDB: Using Linux native AIO
php_1      |   failed to open stream: operation failed
php_1      |
db_1       | 2019-11-19T05:57:28.082551Z 0 [Note] InnoDB: Number of pools: 1
db_1       | 2019-11-19T05:57:28.084792Z 0 [Note] InnoDB: Using CPU crc32 instructions
php_1      |
php_1      | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
php_1      |
db_1       | 2019-11-19T05:57:28.086740Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
php_1      |
php_1      | Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17
php_1      |
php_1      | Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17
db_1       | 2019-11-19T05:57:28.098447Z 0 [Note] InnoDB: Completed initialization of buffer pool
php_1      |
php_1      | Warning: require(/webroot/wizard/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /webroot/wizard/bootstrap/autoload.php on line 17
php_1      |
php_1      | Fatal error: require(): Failed opening required '/webroot/wizard/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /webroot/wizard/bootstrap/autoload.php on line 17

**Comment by mylxsw** [comment]
没有安装 composer 依赖，你可以直接下载下面的 vender.tar.gz ，解压到项目的根目录

https://github.com/mylxsw/wizard/releases/download/1.0.4/vendor.tar.gz

**Comment by qiaobaochen** [comment]
多谢
