### ISSUE TITLE
通过 Docker 安装时数据库初始化错误

### ISSUE THREAD

**Issue by qiaobaochen** [mylxsw/wizard#43]
你好，
host.docker.internal只支持windows和mac系统吧，Ubuntu不支持

根据这个建议，改成自己的IP
[https://github.com/mylxsw/wizard/issues/36](url)

host.docker.internal 改成自己的ip（192.168.1.124或者是docker0 172.17.0.1）为什么还会取访问172.17.0.2？很奇怪

![image](https://user-images.githubusercontent.com/22009264/69205629-7c2b7480-0b85-11ea-80dd-867c78698ae1.png)

**Comment by niezixu** [comment]
你这个错误是表示你没有权限连接你的数据库吧？看下是否开启了远程访问连接

**Comment by ningyanguang666** [comment]
哥哥 您的问题解决了 么 给点经验
