### ISSUE TITLE
docker copose 的安装方法，发送邮件的时候报错

### ISSUE THREAD

**Issue by qiaobaochen** [mylxsw/wizard#44]
"Cannot send message without a sender address"

![image](https://user-images.githubusercontent.com/22009264/69209464-4c369e00-0b92-11ea-8e34-7a3496bb371d.png)

MAIL_DRIVER | "smtp"
-- | --
MAIL_HOST | "smtp.mailtrap.io"
MAIL_PORT | "2525"
MAIL_USERNAME | "null"
MAIL_PASSWORD | "null"
MAIL_ENCRYPTION | "null"

**Comment by mylxsw** [comment]
要发送邮件的话，这几个配置项都必须指定哦

    MAIL_DRIVER=smtp
    MAIL_HOST=smtp.qq.com
    MAIL_PORT=465
    MAIL_USERNAME=admin@example.com
    MAIL_PASSWORD=xxxxxxxx
    MAIL_ENCRYPTION=ssl
    MAIL_FROM_NAME=Wizard
