### ISSUE TITLE
请问execl表格能否做好复制粘贴 复制外面的execl表格到里面来

### ISSUE THREAD

**Issue by Destiny99371** [mylxsw/wizard#51]
![image](https://user-images.githubusercontent.com/49816155/69850558-843c9000-12ba-11ea-8aec-7f17ced8bbfc.png)

**Comment by mylxsw** [comment]
这个目前依赖于 x-spreedsheet 这个开源项目的实现，目前会定期更新这个依赖到最新版本。一旦那边增加了支持，马上跟进。

**Comment by mylxsw** [comment]
目前已经支持从外部 excel 复制到wizard文档，虽然有些小bug，勉强能用
