### ISSUE TITLE
能否增加mermaid流程图的支持

### ISSUE THREAD

**Issue by Q-Action** [mylxsw/wizard#52]
能否增加mermaid流程图的支持

**Comment by mylxsw** [comment]
已加入计划，我先调研调研

**Comment by mylxsw** [comment]
Mermaid 支持已经添加，见 [1.1.0](https://github.com/mylxsw/wizard/releases/tag/1.1.0) 版本。效果参考 [流程图，序列图，饼图，Tex-LaTex-科学公式支持](https://github.com/mylxsw/wizard/wiki/%E6%B5%81%E7%A8%8B%E5%9B%BE%EF%BC%8C%E5%BA%8F%E5%88%97%E5%9B%BE%EF%BC%8C%E9%A5%BC%E5%9B%BE%EF%BC%8CTex-LaTex-%E7%A7%91%E5%AD%A6%E5%85%AC%E5%BC%8F%E6%94%AF%E6%8C%81)
