### ISSUE TITLE
上传图片选择本地上传时，如果因为选错图片，点击取消，图片仍然存在挂载的目录上，没有被删除

### ISSUE THREAD

**Issue by McSiberiaWolf** [mylxsw/wizard#54]
在Markdown格式下，选择上传图片时，如下图：

![image](https://user-images.githubusercontent.com/16216021/71713104-367bf000-2e43-11ea-9b39-ee2ff8a68d91.png)

上图所示，点击本地图片，选择图片后，自动生成`/storage/2020/01-03/wGBzfBTjTuBNzUlm3RL4GVZfnPiFzUBze3tlyW4W.png`图片路径，如果此时发现图片上传错了，选择取消后，图片已上传至服务器上，没有被删除。

```
# docker volume ls
DRIVER              VOLUME NAME
local               my-wizard
# tree /var/lib/docker/volumes/my-wizard/
/var/lib/docker/volumes/my-wizard/
└── _data
    └── 2020
        └── 01-03
            └── wGBzfBTjTuBNzUlm3RL4GVZfnPiFzUBze3tlyW4W.png
```

**备注：**`/webroot/storage/app/public`挂载于本地服务器的`/var/lib/docker/volumes/my-wizard/`下。

## 优化建议

本地上传图片时，发现图片选错后，点击取消，错误图片可以从服务器上删除，避免无用数据冗余。

**Comment by mylxsw** [comment]
感谢建议，暂时图片上传后是不支持删除的，一般上传图片也是低频操作，因此资源并不会有太多浪费
