### ISSUE TITLE
feature/mind分支:思维导图无法保存和无法插入,保存时接口报错Internal Server Error

### ISSUE THREAD

**Issue by zhuangchengwang** [mylxsw/wizard#55]
@mylxsw 官方演示的网站 也是无法插入思维导图，并且 初始化思维导图插件，样式就有问题，高度太少了，在谷歌浏览器和遨游浏览器均出现问题

**Comment by mylxsw** [comment]
思维导图功能还在开发中，还没有正式发布，演示部署的是开发版本，正式发布后我在这里给你回复哈

**Comment by mylxsw** [comment]
自己部署 feature/mind 分支时，需要执行 `php artisan migrate` 命令来做数据库迁移，因为新增了一张表
