### ISSUE TITLE
建议添加附件上传功能

### ISSUE THREAD

**Issue by o624366705** [mylxsw/wizard#58]
建议添加附件上传功能，很有必要！！！

**Comment by mylxsw** [comment]
附件上传是支持的，参考 [项目、文档管理功能说明](https://github.com/mylxsw/wizard/wiki/%E9%A1%B9%E7%9B%AE%E3%80%81%E6%96%87%E6%A1%A3%E7%AE%A1%E7%90%86%E5%8A%9F%E8%83%BD%E8%AF%B4%E6%98%8E#%E6%96%87%E6%A1%A3%E7%AE%A1%E7%90%86%E5%8A%9F%E8%83%BD%E5%8C%BA) - 文档管理功能区 - 2
