### ISSUE TITLE
php artisan migrate:install ERROR:could not find driver

### ISSUE THREAD

**Issue by xiaocimao** [mylxsw/wizard#61]
Hello,朋友们,我尝试用php7.2+mysql5.7+composer+nginx+git的方法搭建wizard.但我以前没用过php,这次使用wizard是头一次安装php7.2,整个过程包括安装composer和php extentions等都是我一步步查资料弄的.
目前我认为环境已经搭建好了，但在执行php artisan migrate:install总是报could not find driver这个错：
In Connection.php line 664:                                                                                                                                                           
  could not find driver (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(191) not null, `batch` int   
  not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')    
                                                                                                           
In PDOConnection.php line 31:                      
  could not find driver  
                        
In PDOConnection.php line 27:                 
  could not find driver  
我知道这可能是个很low的数据库连接错误，但我的DB配置就是将.env.example改成.env后，再更新其中的数据库配置：
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=wizard
DB_USERNAME=root
DB_PASSWORD=root
我通过sqlYog或者命令都是能连上这个数据库的，而且创建了wizard库，请大神位帮忙看下，到底是哪里错了，不胜感激！

**Comment by mylxsw** [comment]
从报错看是因为 php 没有启用 pdo 扩展导致的，检查下是否启用了 pdo 和 pdo_mysql 扩展，如果没有的话，需要先启用才行
