### ISSUE TITLE
LDAP配置不生效问题

### ISSUE THREAD

**Issue by yuyosir** [mylxsw/wizard#62]
LDAP启用并配置了，保存.env后没有生效，重启也不生效，大神帮忙康康呀！ @mylxsw

**Comment by yuyosir** [comment]
# Help!

**Comment by mylxsw** [comment]
用 Docker 方式部署的话，需要在 创建容器 的 Dockerfile 中增加 LDAP 相关的环境变量配置，

![](https://ssl.aicode.cc/prometheus/20200226154653.png)

然后 重新编译部署即可。

    docker build -t my-wizard .
    docker run -d --name my-wizard -p 8080:80  my-wizard

**Comment by yuyosir** [comment]
> 用 Docker 方式部署的话，需要在 创建容器 的 Dockerfile 中增加 LDAP 相关的环境变量配置，
> 
> ![](https://camo.githubusercontent.com/db1f412ae7d92f1e94821b8a95487631add9060b/68747470733a2f2f73736c2e6169636f64652e63632f70726f6d6574686575732f32303230303232363135343635332e706e67)
> 
> 然后 重新编译部署即可。
> 
> ```
> docker build -t my-wizard .
> docker run -d --name my-wizard -p 8080:80  my-wizard
> ```

多谢大佬，我试试！

**Comment by yuyosir** [comment]
加入LDAP环境变量配置后运行build报错如下：
Error response from daemon: Dockerfile parse error line 18: unknown instruction: WIZARD_USE_LDAP=TRUE
您帮忙看看是哪里的问题呢？

**Comment by mylxsw** [comment]
每一个环境变量前需要加  `ENV`，不好意思，图片上贴的时候我没注意

![](https://ssl.aicode.cc/prometheus/20200226162445.png)

**Comment by yuyosir** [comment]
终于配置成功啦，多谢你大神！

**Comment by yuyosir** [comment]
呃，还有个litlle问题要麻烦您，这个邮箱地址可以换成域账号吗，在哪里改呢(#^.^#)

**Comment by krisbai** [comment]
> 呃，还有个litlle问题要麻烦您，这个邮箱地址可以换成域账号吗，在哪里改呢(#^.^#)

哥们能贴下你的ldap配置吗？我ldap配置没生效，谢谢！
