### ISSUE TITLE
php报错

### ISSUE THREAD

**Issue by ningyanguang666** [mylxsw/wizard#64]
访问也页面是
该网页无法正常运作
 目前无法处理此请求。
HTTP ERROR 500

[27-Feb-2020 04:57:29 UTC] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/webroot/wizard/public/index.php on line 50

/data/webroot/wizard/public/index.php 的50行如下：
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

请问我这是什么故障

**Comment by mylxsw** [comment]
补充下环境信息，PHP版本，估计是版本太低了，Wizard最低支持 PHP 7.2 以上版本

**Comment by ningyanguang666** [comment]
我这个手动搭建的方式，环境已经失败了
我用docker的方式搭建了，但是又遇到问题了
centos7.7，mysql8.0.19
报错如下，请您帮忙看一下，谢谢
[root@localhost data]# docker run -it --rm --name my-wizard my-wizard php artisan migrate:install

In Connection.php line 664:
                                                                                                                                                                   
  SQLSTATE[HY000] [2002] No such file or directory (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(19  
  1) not null, `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')                                                                   
                                                                                                                                                                   

In PDOConnection.php line 31:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In PDOConnection.php line 27:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by mylxsw** [comment]
数据库访问地址错误导致的，启动镜像的时候，数据库连接地址的环境变量需要修改为 MySQL 所在服务器的 IP 地址（非 127.0.0.1）。

**Comment by ningyanguang666** [comment]
好的 谢谢 我再试一下 
我用docker搭建的好像成功了 页面能访问 但是有这个报错 您帮忙再看一下
[root@host webroot]# docker run -it --rm --name my-wizard -p 8080:80  my-wizard
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message

**Comment by mylxsw** [comment]
这个不影响应用的功能，如果介意的话，在创建镜像的时候，加一下这一句 `RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf` 到 Dockerfile 中，然后重新编译启动就可以了

最终的 Dockerfile 这样

	FROM mylxsw/wizard:latest
   
	# 添加下面这一行在这里
	RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

	ENV DB_CONNECTION=mysql
	ENV DB_HOST=host.docker.internal
	ENV DB_PORT=3306
	ENV DB_DATABASE=wizard
	ENV DB_USERNAME=wizard
	ENV DB_PASSWORD=wizard
	ENV WIZARD_NEED_ACTIVATE=false

	ENV APP_URL=http://localhost:8080

	# 文件上传存储目录
	VOLUME /webroot/storage/app/public

	RUN php artisan config:cache

也可以不改，不影响功能，在下一个版本中会解决掉。

**Comment by ningyanguang666** [comment]
感谢
