### ISSUE TITLE
使用感受及优化建议！

### ISSUE THREAD

**Issue by yuyosir** [mylxsw/wizard#67]
**一、使用感受：**
1. 主要还是项目权限，形成规模之后权限管理就显得格外重要，各个部门之间都会有一些私有文档放上去，目前的权限管理只适合中小型公司，如果人员规模庞大，只靠系统管理员维护会很吃力；
2. 默认是使用邮箱地址登陆的，用户登陆需要输入冗长的邮箱后缀，一般公司内部出了邮箱系统其它的系统几乎没有用邮箱地址登陆的，用户登陆的体验不太好。

**二、优化建议：**
1. 可以使用LDAP用户组结合wizard用户组以公司现有的组织架构来管理权限，节省维护成本；
1.1 项目结构：项目目录(系统管理员创建并管理)-团队(引入”语雀"中团队的概念)(每个用户都可以创建并管理)-项目(用户创建并管理)；
    1.1.1 项目结构中增加1个团队(目录)，用户可以自行创建团队并添加成员及用户组(引入"语雀"团队的概念来管理)；
    1.1.2 用户组可以分两种，一种在整个wizard中适用(由系统管理员维护)，一种只在团队中适用(由团队创建人维护)。
    1.1.3 在团队下属的项目中，权限可以再细分：
    团队创建人可以自行添加单个成员和用户组(目前的项目中只能添加用户组，而用户组需要系统管理员来维护，比较吃力)，团队创建人可以在自己的团队中创建用户组，方便在团队内管理权限划分；
    1.1.4 如果不创建团队，属于个人项目，则默认没有项目目录或者放在管理员划分的项目目录中，也可以在个人项目中添加成员或用户组。
    1.1.5 模板共享中建议也可以加上用户组或成员的权限管理，目前给他人共享应该是所有人吧，如果想把隐私的模板共享给指定成员或用户组是没有办法的。
2. 可以自行配置登陆时使用用户名(邮箱前缀)或邮箱地址登陆。

**以上，仅供参考。
谢谢！**

**Comment by ningyanguang666** [comment]
能给点docker搭建前的准备工作么，谢谢

**Comment by yuyosir** [comment]
> 能给点docker搭建前的准备工作么，谢谢

要先配置MySQL数据库，部署的时候把数据库参数放到dockerfile里就行

**Comment by ningyanguang666** [comment]
这是我的dockerfile
FROM mylxsw/wizard:latest

ENV DB_CONNECTION=mysql
ENV DB_HOST=localhost
ENV DB_PORT=3306
ENV DB_DATABASE=wizard_2
ENV DB_USERNAME=wizard
ENV DB_PASSWORD=wizard
ENV WIZARD_NEED_ACTIVATE=false

VOLUME /webroot/storage/app/public
但是吃初始化数据库报错了 
In Connection.php line 664:
                                                                                                                                                                   
  SQLSTATE[HY000] [2002] No such file or directory (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(19  
  1) not null, `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')                                                                   
                                                                                                                                                                   

In PDOConnection.php line 31:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In PDOConnection.php line 27:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by mylxsw** [comment]
非常感谢，这些建议都很中肯，接下来有我会找时间对这几个方面进行优化

**Comment by stardyun** [comment]
> 这是我的dockerfile
> FROM mylxsw/wizard:latest
> 
> ENV DB_CONNECTION=mysql
> ENV DB_HOST=localhost
> ENV DB_PORT=3306
> ENV DB_DATABASE=wizard_2
> ENV DB_USERNAME=wizard
> ENV DB_PASSWORD=wizard
> ENV WIZARD_NEED_ACTIVATE=false
> 
> VOLUME /webroot/storage/app/public
> 但是吃初始化数据库报错了
> In Connection.php line 664:
> 
> SQLSTATE[HY000] [2002] No such file or directory (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(19
> 
> 1. not null, `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
> 
> In PDOConnection.php line 31:
> 
> SQLSTATE[HY000] [2002] No such file or directory
> 
> In PDOConnection.php line 27:
> 
> SQLSTATE[HY000] [2002] No such file or directory

我也是这个错

**Comment by mylxsw** [comment]
数据库连接地址不对，不能使用 localhost，你数据库如果是部署在宿主机上的话，那么数据库地址应该为 `host.docker.internal`或者宿主机的 IP 地址

**Comment by ningyanguang666** [comment]
谢谢 已经解决了

**Comment by stardyun** [comment]
> 数据库连接地址不对，不能使用 localhost，你数据库如果是部署在宿主机上的话，那么数据库地址应该为 `host.docker.internal`或者宿主机的 IP 地址

试了，用host.docker.internal 和 宿主机ip都不可以

**Comment by mylxsw** [comment]
描述一下宿主机系统是什么，数据库，账号，权限是否已经创建、分配，Dockerfile 配置

**Comment by stardyun** [comment]
> 描述一下宿主机系统是什么，数据库，账号，权限是否已经创建、分配，Dockerfile 配置

docker下的mysql8.0.16，root账号。

**Comment by stardyun** [comment]
> > 描述一下宿主机系统是什么，数据库，账号，权限是否已经创建、分配，Dockerfile 配置
> 
> docker下的mysql8.0.16，root账号。

PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]

**Comment by mylxsw** [comment]
这个错误是因为 mysql 8.0 默认的鉴权方法和之前的不一样，用下面的语句重新创建账号就可以了

    ALTER USER '用户名'@'主机地址' IDENTIFIED WITH mysql_native_password BY '密码';

**Comment by stardyun** [comment]
> 这个错误是因为 mysql 8.0 默认的鉴权方法和之前的不一样，用下面的语句重新创建账号就可以了
> 
> ```
> ALTER USER '用户名'@'主机地址' IDENTIFIED WITH mysql_native_password BY '密码';
> ```

问题解决，感谢
