### ISSUE TITLE
报错docker run -it --rm --name my-wizard my-wizard php artisan migrate:install

### ISSUE THREAD

**Issue by ningyanguang666** [mylxsw/wizard#68]
centos7.7，mysql8.0.19
报错如下，请您帮忙看一下，谢谢
[root@localhost data]# docker run -it --rm --name my-wizard my-wizard php artisan migrate:install

In Connection.php line 664:

SQLSTATE[HY000] [2002] No such file or directory (SQL: create table migrations (id int unsigned not null auto_increment primary key, migration varchar(19

not null, batch int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] No such file or directory

In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] No such file or directory

**Comment by ningyanguang666** [comment]
这是我的Dockerfile
FROM mylxsw/wizard:latest

# 数据库连接配置
# 这里可以根据需要添加其它的Env配置，可用选项参考项目的.env.example文件
ENV DB_CONNECTION=mysql
ENV DB_HOST=localhost
ENV DB_PORT=3306
ENV DB_DATABASE=wizard_2
ENV DB_USERNAME=wizard
ENV DB_PASSWORD=wizard
ENV WIZARD_NEED_ACTIVATE=false

# 文件上传存储目录
VOLUME /webroot/storage/app/public

RUN php artisan config:cache

**Comment by yuyosir** [comment]
你数据库配置了吗？

**Comment by ningyanguang666** [comment]
数据库是8.0.19，这么配置的
mysql> create database wizard_2;

mysql> CREATE USER 'wizard'@'%' IDENTIFIED BY 'wizard';

mysql> GRANT ALL PRIVILEGES ON wizard.* TO 'wizard'@'%' WITH GRANT OPTION;

**Comment by yuyosir** [comment]
数据库是宿主机的？
我的数据库是宿主机的，
dockerfile 里是这么配置的：
`ENV DB_HOST=host.docker.internal`

**Comment by ningyanguang666** [comment]
您的意思是宿主机不需要安装mysql 
dockerfile里直接配置就可以了是么

**Comment by yuyosir** [comment]
不是，docker里没有数据库，我只是给你举个例子。

**Comment by ningyanguang666** [comment]
哦哦 我把用户改成root试一下

**Comment by yuyosir** [comment]
你如果用的是宿主机的数据库，DB_HOST不是localhost，你换成`ENV DB_HOST=host.docker.internal试试

`

**Comment by ningyanguang666** [comment]
嗯 已经换成ENV DB_HOST=host.docker.internal了，我怀疑是权限不够 写表写不进去

**Comment by yuyosir** [comment]
嗯，那你先用root试试吧

**Comment by ningyanguang666** [comment]
嗯嗯 谢谢啦  我已经把之前的删了 再重新拉取一遍
