### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by XingshengLiu** [mylxsw/wizard#70]
按照文档中docker部署中方法一操作，访问500

**Comment by mylxsw** [comment]
数据库地址对了吗？然后贴一下你的命令看看呢

**Comment by umi-soft** [comment]
`docker run -d --name code-document \
    -e DB_HOST=docker.host.internal \
    -e DB_PORT=9001  \
    -e DB_DATABASE=wizard  \
    -e DB_USERNAME=root  \
    -e DB_PASSWORD=umisoft.cn  \
    -p 9000:80 \
    -v /Users/hujie/Documents/dev/documents:/webroot/storage/app/public   \
    mylxsw/wizard`
9000端口浏览器访问出现500错误
我是首次安装，按照您的文档成功执行了以下代码：
`php artisan migrate:install
php artisan migrate`

数据库本地机器访问没有问题，路径文件夹也创建了

**Comment by umi-soft** [comment]
奇怪的是我访问http://localhost:9000/register，页面正常，访问http://localhost:9000/页面500错误

**Comment by umi-soft** [comment]
![image](https://user-images.githubusercontent.com/13619406/79102548-86047d00-7d9d-11ea-872e-4fd6e6585acf.png)

**Comment by umi-soft** [comment]
php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select `wz_project_catalogs`.*, (select count(*) from `wz_projects` where `wz_project_catalogs`.`id` = `wz_projects`.`catalog_id` and `wz_projects`.`deleted_at` is null) as `projects_count` from `wz_project_catalogs` where `show_in_home` = 1 order by `sort_level` asc)

**Comment by umi-soft** [comment]
我找到原因了，host.docker.internal被我写成了docker.host.internal
