### ISSUE TITLE
求教功能菜单不显示的问题？

### ISSUE THREAD

**Issue by flyfeng2002** [mylxsw/wizard#71]
安装完成，正常注册用户，登陆也正常，创建项目、目录都没问题，就是点进项目，左列功能菜单是空白的，上面也没功能图标，是什么情况呢？

**Comment by mylxsw** [comment]
截个图看看

**Comment by flyfeng2002** [comment]
![TIM截图20200305142616](https://user-images.githubusercontent.com/26499513/75954476-be878000-5eee-11ea-91f6-59a065267d98.png)
就是上图，啥按钮都没有，没法添加文档啥的

**Comment by mylxsw** [comment]
参考这个 [如何新增项目](https://github.com/mylxsw/wizard/wiki/%E5%A6%82%E4%BD%95%E6%96%B0%E5%A2%9E%E9%A1%B9%E7%9B%AE)

**Comment by flyfeng2002** [comment]
好的，已解决。顺便提交一个小bug，思维导图下添加下一级时，直接会失去当前编辑焦点，下边框拖动条会自动到最左边，右侧边框拖动会自动到最上面。
