### ISSUE TITLE
1.1.0升到1.2.1后导出pdf用不了

### ISSUE THREAD

**Issue by benfeng** [mylxsw/wizard#72]
1。上传文档也用不了
upload  500
![image](https://user-images.githubusercontent.com/1662310/75953167-c3970000-5eeb-11ea-8507-7ebe65adef46.png)

2。导出pdf也是等了好久，之后500

这与目录权限有关吗

**Comment by mylxsw** [comment]
部署方式用的独立部署还是 Docker ？

**Comment by benfeng** [comment]
docker

**Comment by benfeng** [comment]
1，上传文档 不挂载是正常的

2，导出pdf不知是什么题
