### ISSUE TITLE
1.2.0版本上传附件后，点击下载附件报资源不存在

### ISSUE THREAD

**Issue by chanvee** [mylxsw/wizard#73]
大神您好:
1.2.0版本上传附件后，点击下载附件报资源不存在

**Comment by mylxsw** [comment]
详细说下安装环境呢

- 部署方式：Docker 还是独立部署？
- 附件下载地址

**Comment by chanvee** [comment]
> 详细说下安装环境呢
> 
> * 部署方式：Docker 还是独立部署？
> * 附件下载地址

部署方式：独立部署
附件下载地址：类似于http://wizard.com:8080/storage/2020/03-05/WozvNc6qV7PjdoMqt989eBxT711z7cOCHJXSD9az.xlsx，查了服务器上文件是存在的

**Comment by chanvee** [comment]
> 详细说下安装环境呢
> 
> * 部署方式：Docker 还是独立部署？
> * 附件下载地址

文件实际存放地址是在根目录/storage/app/public下，如果把文件拷到根目录/public/storage下则可以下载，请问下是不是独立部署要在哪个地方设置下下载路径？

**Comment by chanvee** [comment]
可以了，是因为我没有执行建立软连接php artisan storage:link这一步
