### ISSUE TITLE
[FEATURE] 能否加一个从Showdoc文档导入的功能

### ISSUE THREAD

**Issue by Ecareyu** [mylxsw/wizard#75]
大佬，showdoc那种存储到sqlite的方式，实在不方便运维，奈何作者死犟，我又找不到相对更好的文档系统，现在终于找到了wizard，但是，目前我们的文档堆积已经不少了，如果一篇篇迁移的话，时间成本略高，所以能否加一个showdoc文档迁移功能。

**Comment by mylxsw** [comment]
这个我研究下，之前就想过这个功能，但是奈何一直没有需求

**Comment by Ecareyu** [comment]
哈哈，现在有了，大佬你要是近期就做的话，我就再观望一下。等你搞好了，我就上。现在我们30多个项目，文档太多了，手动搞起来是真的麻烦。

**Comment by mylxsw** [comment]
迁移工具第一版已经做好了，有时间可以试试，项目地址为 https://github.com/mylxsw/wizard-migration，直接到 Release 下载对应系统的可执行文件就可以了

**Comment by Ecareyu** [comment]
大佬，果然是世界上最快的男人[doge]，我这就去试试。

**Comment by Ecareyu** [comment]
docker镜像下载太慢了，我刚下载好，但是跑不起来。我这边是直接用的docker-compose启动，启动完后发现貌似没有执行composer-install，所以我是不是还需要用docker exec 去安装下laravel依赖？

**Comment by mylxsw** [comment]
别用 docker-compose 启动，直接用 docker 容器的方式启动吧，docker-compose 这个好久没用了，不确定还能不能用

**Comment by Ecareyu** [comment]
ok

**Comment by Ecareyu** [comment]
Dockerfile里的composer源地址换一下吧，laravel-china那个不是停服了吗？阿里云或者安畅的可能比较稳一点。

**Comment by Ecareyu** [comment]
docker安装完了以后，数据库没有跑，所以会导致500，我估计有些issue说的安装完了500就是这个原因。
