### ISSUE TITLE
手动部署图片无法粘贴自动上传

### ISSUE THREAD

**Issue by itq5** [mylxsw/wizard#77]
1、在线演示环境可以直接截图自动上传，但是手动部署的无法实现
![image](https://user-images.githubusercontent.com/42521985/76435241-b39e8500-63f1-11ea-9d5a-90d6a3eb8e11.png)

2、需要手动上传图片文件，是否能支持图片本地保存和直接上传七牛云等功能
![image](https://user-images.githubusercontent.com/42521985/76435292-c9ac4580-63f1-11ea-9452-1f0a03fb91e2.png)

**Comment by yuyosir** [comment]
我之前也有过，把所有webroot下的文件替换成新的就好了
