### ISSUE TITLE
注册跳转后网页500错误

### ISSUE THREAD

**Issue by XiaoNuoZ** [mylxsw/wizard#78]
用的第一种方法，因为只有一个步骤很简单，就把端口改成了8081 （系统是ubuntu18）
![image](https://user-images.githubusercontent.com/46923935/77637124-241bd900-6f90-11ea-80aa-a34cfc9b70a2.png)

然后访问http://127.0.0.1:8081/register  可以访问    login也可以访问
但是注册账号页面提交后直接500错误

![image](https://user-images.githubusercontent.com/46923935/77637545-cdfb6580-6f90-11ea-8586-3c27ca28b92e.png)

**Comment by XiaoNuoZ** [comment]
大佬，我还有个是在公司内网搭建的，用的是手动搭建的方法，目前也是网页500错误

**Comment by mylxsw** [comment]
用 Docker 启动的时候，命令用这个，启用 DEBUG 模式，再访问看看报错是啥

    docker run -it --rm --name wizard -e DB_HOST=host.docker.internal -e DB_PORT=3306 -e DB_DATABASE=wizard -e DB_USERNAME=wizard -e DB_PASSWORD=wizard -e APP_DEBUG=true -p 8080:80 -v /Users/mylxsw/Downloads:/webroot/storage/app/public  mylxsw/wizard

就是在命令参数中，添加了一个 `-e APP_DEBUG=true` 的选项

**Comment by mylxsw** [comment]
自己独立搭建的环境把 APP_DEBUG 那个配置项改成 true，这样访问的时候就显示具体报错原因了

**Comment by XiaoNuoZ** [comment]
> 自己独立建造的环境把APP_DEBUG那个配置项改成true，这样访问的时候就显示具体报错原因了

好的，感谢大佬

**Comment by XiaoNuoZ** [comment]
> 自己独立建造的环境把APP_DEBUG那个配置项改成true，这样访问的时候就显示具体报错原因了

非常感谢，手动部署的问题解决了，是权限问题，我给项目文件的属主和属组都是nginx，现在我把整个文件夹权限改成755后就可行了。但是我想问一下这个项目属主用户是需要自己创建一个普通用户来控制这个项目么

**Comment by mylxsw** [comment]
这个本身与这个项目无关，从安全的角度看，最好是单独建立一个用户，注意，nginx/php-fpm 都要使用同一个用户（非root，比如 www 用户），否则可能会出现访问权限问题。

**Comment by XiaoNuoZ** [comment]
> 这个本身与这个项目无关，从安全的角度看，最好是单独建立一个用户，注意，nginx/php-fpm 都要使用同一个用户（非root，比如 www 用户），否则可能会出现访问权限问题。

![image](https://user-images.githubusercontent.com/46923935/77721081-c4234200-7024-11ea-8890-16d6e10199f5.png)
大佬，出现了这个问题，原因是在vendor中，vendor我是直接下载的，并没有用composer ，因为下的很久，直到断开连接都没有下载完成，换了国内源也是如此

**Comment by XiaoNuoZ** [comment]
> 这个本身与这个项目无关，从安全的角度看，最好是单独建立一个用户，注意，nginx/php-fpm 都要使用同一个用户（非root，比如 www 用户），否则可能会出现访问权限问题。

该如何解决这个问题呢

**Comment by XiaoNuoZ** [comment]
> 这个本身与这个项目无关，从安全的角度看，最好是单独建立一个用户，注意，nginx/php-fpm 都要使用同一个用户（非root，比如 www 用户），否则可能会出现访问权限问题。

![image](https://user-images.githubusercontent.com/46923935/77735739-0b6dfa80-7046-11ea-9d98-8ba30fa0acaf.png)
大佬，这是dockerb部署的错误，完全抓瞎啊

**Comment by aplgsd** [comment]
> > 这个本身与这个项目无关，从安全的角度看，最好是单独建立一个用户，注意，nginx/php-fpm 都要使用同一个用户（非root，比如 www 用户），否则可能会出现访问权限问题。
> 
> ![image](https://user-images.githubusercontent.com/46923935/77735739-0b6dfa80-7046-11ea-9d98-8ba30fa0acaf.png)
> 大佬，这是docker部署的错误，完全抓瞎啊

我这边也是一样的问题

**Comment by mylxsw** [comment]
这个问题是数据库连接地址配置 错误产生的，配置文件可以贴出来看下。可以参考下 #60 #68 #43 

> Docker 部署，MySQL 如果实在宿主机上的，访问地址用 host.docker.internal 或者宿主机的 IP 地址（不能用 localhost/127.0.0.1）

**Comment by aplgsd** [comment]
> > > 这个本身与这个项目无关，从安全的角度看，最好是单独建立一个用户，注意，nginx/php-fpm 都要使用同一个用户（非root，比如 www 用户），否则可能会出现访问权限问题。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/46923935/77735739-0b6dfa80-7046-11ea-9d98-8ba30fa0acaf.png)
> > 大佬，这是docker部署的错误，完全抓瞎啊
> 
> 我这边也是一样的问题

我这边的问题解决了，是因为没有进行数据库初始化
因为用的是docker部署方法一，
以为会自行进行数据库初始化的。

**Comment by mylxsw** [comment]
> > > > 这个本身与这个项目无关，从安全的角度看，最好是单独建立一个用户，注意，nginx/php-fpm 都要使用同一个用户（非root，比如 www 用户），否则可能会出现访问权限问题。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/46923935/77735739-0b6dfa80-7046-11ea-9d98-8ba30fa0acaf.png)
> > > 大佬，这是docker部署的错误，完全抓瞎啊
> > 
> > 
> > 我这边也是一样的问题
> 
> 我这边的问题解决了，是因为没有进行数据库初始化
> 因为用的是docker部署方法一，
> 以为会自行进行数据库初始化的。

OK，了解了，是我在文档里面忘记写这一部分了，等会儿我补上

**Comment by XiaoNuoZ** [comment]
大佬，关于升级这块能不能详细一点呢，没使用过git命令，我这拉取是不是还要在我服务器上创建一个分支才能拉取？还是一条命令就行

**Comment by mylxsw** [comment]
一般情况下，git命令部分就只有一条命令，在项目目录下执行 `git pull` 就可以了，还有要注意看升级的版本 release 说明，是否有需要执行数据库迁移或者依赖更新部分。

**Comment by XiaoNuoZ** [comment]
> 一般情况下，git命令部分就只有一条命令，在项目目录下执行 `git pull` 就可以了，还有要注意看升级的版本 release 说明，是否有需要执行数据库迁移或者依赖更新部分。

= =    我在.git目录下输  git pull https://github.com/mylxsw/wizard.git  行吗

**Comment by XiaoNuoZ** [comment]
> > 一般情况下，git命令部分就只有一条命令，在项目目录下执行 `git pull` 就可以了，还有要注意看升级的版本 release 说明，是否有需要执行数据库迁移或者依赖更新部分。
> 
> = = 我在.git目录下输 git pull https://github.com/mylxsw/wizard.git 行吗

报错了，项目文件下报错
![image](https://user-images.githubusercontent.com/46923935/79319805-63a86600-7f3b-11ea-9d24-2146bb3023ab.png)
.git文件下拉取后报错
![image](https://user-images.githubusercontent.com/46923935/79319851-74f17280-7f3b-11ea-81aa-1b85c8cb5440.png)
大佬   这种情况怎么解决呀

**Comment by mylxsw** [comment]
在项目根目录下执行，不能在 .git 目录下执行
