### ISSUE TITLE
是否支持https访问？

### ISSUE THREAD

**Issue by lnytx** [mylxsw/wizard#79]
我们从外部使用https访问到该应用，但是打开内部的项目文档，默认都是生成的http形式的url，导致报了404错误。

**Comment by mylxsw** [comment]
生成http形式的url这个是在哪里生成的？项目本身是支持https的，在nginx上面https的配置就可以了，链接地址如果有问题，可以修改配置文件中的 `APP_URL` 为正确的地址试试（独立部署 修改 .env 文件，docker部署可以指定环境变量  APP_URL）

**Comment by smokesea** [comment]
好像和我是一个问题，APP_URL好像不太灵

**Comment by squallliu** [comment]
如果 nginx 做 https 反代的话，加 proxy_set_header X-Forwarded-Proto $scheme;

**Comment by mylxsw** [comment]
各位能否详细描述下你们是怎么配置的https呢，还有配置后访问哪个地址是有问题的，我今天将演示站点配置了一份https的，就按照最简单的配置方法，在nginx上加了个证书，改了下端口就ok了，页面我都点开看了下，都是ok的

**Comment by mylxsw** [comment]
已经把所有 route 替换了，所有链接地址不带域名，用https反向代理应该没问题了，更新到最新版就可以 （1.2.2）
