### ISSUE TITLE
有没有更详细的安装说明

### ISSUE THREAD

**Issue by xiehongxin** [mylxsw/wizard#8]
作者您好，我感觉您开发的这个工具非常适合我们，请问有没有更详细的安装说明？

**Comment by mylxsw** [comment]
项目是使用PHP7.2开发的，因此，需要先安装php7.2以及nginx，下载一下composer，这个的教程网上一大片，就不赘述了。

然后就是项目的配置了，使用`git clone`下载项目之后，到项目的目录中去，执行 `composer install` 命令安装依赖

    composer install --prefer-dist

> 如果没有配置composer到环境变量的话，需要这样执行
>     /path/to/php/bin/php /path/to/composer/composer.phar install --prefer-dist

接下来，安装配置数据库，默认使用MySQL数据库，拷贝一份项目的配置文件

    cp .env.example .env

然后修改一下其中关于MySQL的连接信息，之后，在项目目录下执行下面的配置命令就可以了

    php artisan migrate:install
    php artisan migrate

最后，因为要支持文件上传功能，所以再执行一下下面这个命令就OK了

    php artisan storage:link

总之，没什么特别的，就是一个普通的PHP项目(Laravel项目)，实在不懂百度一下，教程还是很多的。
