### ISSUE TITLE
Wizard位于Nginx后并且在独立路径下无法访问

### ISSUE THREAD

**Issue by smokesea** [mylxsw/wizard#80]
场景：位于域名的路径下，反向代理。
比如手头有一个www.abc.com，proxy_pass /wizard/ http://wizard.host 
查看容器有访问请求，报告太多重定向

**Comment by mylxsw** [comment]
Wizard目前不支持这种代理方式，如果非要配置的话可以试试nginx的 sub_filter， 不过要替换的路径会很多，配置好了也可能会有一大堆问题
