### ISSUE TITLE
首页的最近活动同一文档差异内容全部一样和https的支持

### ISSUE THREAD

**Issue by squallliu** [mylxsw/wizard#81]
1. 首页的最近活动的每条活动的差异都是最后一次修改文档的差异
2. 好像并不支持 https, route 生成的链接总是 http(AppServiceProvider 中加 \URL::forceScheme('https'); 好了)

**Comment by mylxsw** [comment]
首页差异这个我这两天找时间再看看，第二个我今天配置了个https的，发现是ok的，能否说下你是怎么配置的呢，还有哪个页面有问题呢

**Comment by squallliu** [comment]
docker部署，nginx https反向代理
左边树形导航和全部通知已读

**Comment by squallliu** [comment]
有什么新的进展吗？

**Comment by mylxsw** [comment]
https 问题已经解决了，升级到最新版 1.2.2 即可

**Comment by squallliu** [comment]
已经升级，确实解决了
