### ISSUE TITLE
获取最近操作日志失败

### ISSUE THREAD

**Issue by umi-soft** [mylxsw/wizard#82]
接口：/operations/recently?limit=project&project_id=1
返回错误信息如下：
Trying to get property 'username' of non-object (View: /webroot/resources/views/operations/recently.blade.php)

我在未退出登录情况下，关闭了docker，重新打开后，进行重启服务，登录成功后，出现上述错误

**Comment by umi-soft** [comment]
我清理了wz_operation_logs表数据后，接口正常了

**Comment by mylxsw** [comment]
应该是强制关闭操作日志表数据有不完整，近期我会更新下，做个降级处理，避免报错

**Comment by umi-soft** [comment]
大佬，我看到发布1.2.2了，啥时候有时间处理下这个问题呢，我发现只要是意外关闭，就会造成这个问题

**Comment by mylxsw** [comment]
这个问题的修复只是对新用户有效，是把操作日志表的存储引擎修改为 InnoDB了，你可以这样做，连接到数据库，执行下面的命令，将这个表的 ARCHIVE 存储引擎切换为 InnoDB

    alter table wz_operation_logs engine=innodb;
