### ISSUE TITLE
Undefined variable: catalogs (View: /data/webroot/wizard/resources/views/user-home.blade.php)

### ISSUE THREAD

**Issue by XiaoNuoZ** [mylxsw/wizard#84]
我1.2.0版本无法升级到1.2.1，原因是1.2.0是解压出来的，没有git文件，现在用git下载了1.2.1后替换了原来的版本，但是数据库因为有数据并没有重新弄，即没进行数据库命令
![image](https://user-images.githubusercontent.com/46923935/79422687-e7238f00-7fef-11ea-87a1-a2b71c899119.png)

现在在home页面下报了这个错误，大佬，请问如何解决？
![image](https://user-images.githubusercontent.com/46923935/79422763-06222100-7ff0-11ea-88f9-563ae43bc2eb.png)

**Comment by mylxsw** [comment]
直接到项目根目录下，执行数据迁移命令 `php  artisan migrate` 就可以了

**Comment by XiaoNuoZ** [comment]
> 直接到项目根目录下，执行数据迁移命令 `php artisan migrate` 就可以了

![image](https://user-images.githubusercontent.com/46923935/79550504-fe837a80-80ca-11ea-9508-d6a6a35817cb.png)
大佬  数据库是以前1.2.0的，有很多数据了，这怎么解决啊

**Comment by XiaoNuoZ** [comment]
> 直接到项目根目录下，执行数据迁移命令 `php artisan migrate` 就可以了

我把新下载的1.2.1的包里的.git文件夹复制到以前的1.2.0版本中进行更新了，但是他提示Already up-to-date.  大佬，这个.git文件夹里面改啥配置可以让他进行更新啊

**Comment by mylxsw** [comment]
git 没有这么操作的啊，不要随便修改 .git 文件，如果实在没法更新的话，你就下载最新版，然后覆盖到原来的版本就可以了
