### ISSUE TITLE
文档排序是不是有问题，无法修改，自动变成0

### ISSUE THREAD

**Issue by AmazingXiaomi** [mylxsw/wizard#85]
![image](https://user-images.githubusercontent.com/30220803/79429362-fd364d00-7ff9-11ea-8b00-2a7154346bf1.png)

**Comment by mylxsw** [comment]
文档排序有个隐藏逻辑，就是如果文档是目录的话，会自动的排在前面，所以排序规则是这样的

- 目录文档在最前面，如果多个都是目录文档，则按照排序序号排列
- 普通文档在最后面，多个按照排序序号排列

**Comment by AmazingXiaomi** [comment]
原来如此，谢啦

**Comment by qiujianzhong** [comment]
感觉设计不太合理
