### ISSUE TITLE
excel保存的时候有问题

### ISSUE THREAD

**Issue by xyls518** [mylxsw/wizard#86]
/project/1/doc post提交报422
{"content":["\u9875\u9762\u5185\u5bb9\u4e0d\u5408\u6cd5\uff0c\u8868\u683c\u9875\u9762\u5fc5\u987b\u4e3a\u5408\u6cd5\u7684json\u683c\u5f0f"]}

**Comment by mylxsw** [comment]
页面内容不合法，表格页面必须为合法的json格式

保存的时候做了内容完整性校验的，应该是前端页面有啥报错了，你保存的时候右键，审查元素，看看控制台是否有报错呢，贴出来看下

**Comment by xyls518** [comment]
很明显的看到content 为undefine

**Comment by xyls518** [comment]
你的整个  content: $.global.getEditorContent() 完全拿不到数据

**Comment by mylxsw** [comment]
因为最近升级了表格控件，新建表格文档会有这个问题，已修复，更新到最新版 （1.2.2）就可以了
