### ISSUE TITLE
请问作者啥时候有一个重置密码的功能

### ISSUE THREAD

**Issue by Destiny011** [mylxsw/wizard#90]
很多人会出现账户不合法 但是密码是没问题的  就是登录不成功 我想请问下能否加个重置密码的功能 我在数据库改密码 发现并没有什么用

**Comment by mylxsw** [comment]
登录页面有“找回密码”，再配置文件里面配置好邮件发送配置后，这里的找回密码会发送一封密码重置邮件，用这个来重置

**Comment by Destiny011** [comment]
需要这么麻烦吗  我想直接一个重置密码界面就好 强制性修改

**Comment by Destiny011** [comment]
我等下试试配置下
