### ISSUE TITLE
v1.2.2版登入界面显示HTML源码

### ISSUE THREAD

**Issue by McSiberiaWolf** [mylxsw/wizard#96]
版本从 `v1.2.0` 升级到 `v1.2.2` 后，登入都正常，就是登入界面显示 HTML 源码

![image](https://user-images.githubusercontent.com/16216021/82402658-917b5000-9a8f-11ea-829e-d714cff25832.png)

**Comment by mylxsw** [comment]
这个是做了个这种背景图啊，可以添加配置项 `WIZARD_LOGIN_BACKGROUND_IMG` 来替换成其他的

    WIZARD_LOGIN_BACKGROUND_IMG=/assets/background-image.jpeg

**Comment by McSiberiaWolf** [comment]
原来如此，图片在项目的这个地址：[background-image.jpeg](https://github.com/mylxsw/wizard/blob/master/public/assets/background-image.jpeg)

v1.2.0 版本没有这个设置，如果其他人有需求，可以增加这个环境变量设置背景图片，建议默认还是原来没有背景较好。
