### ISSUE TITLE
Ldap登录时提示账户信息不合法,哪位帮忙康康呀？

### ISSUE THREAD

**Issue by krisbai** [mylxsw/wizard#99]
----已下为配置信息---- 
 WIZARD_USE_LDAP=true
  LDAP_LOGGING=true
  LDAP_ACCOUNT_PREFIX=uid=
  LDAP_ACCOUNT_SUFFIX=,dc=xxx,dc=com
  LDAP_HOSTS=xxx
  LDAP_PORT=389
  LDAP_BASE_DN=dc=xxx,dc=com
  LDAP_USERNAME=cn=admin,dc=xxx,dc=com
  LDAP_PASSWORD=xxx
  LDAP_USE_SSL=false
  LDAP_USE_TLS=false
  LDAP_PASSWORD_SYNC=true
  LDAP_LOGIN_FALLBACK=true
  LDAP_SYNC_NAME_ATTR=displayname

**Comment by mylxsw** [comment]
OpenLDAP 还是 ActiveDirectory?

参考下这个

https://github.com/mylxsw/wizard/issues/15

**Comment by krisbai** [comment]
> #15

你好，是LDAP，就是参考的这个配置。怀疑是LDAP_ACCOUNT_PREFIX=和LDAP_ACCOUNT_SUFFIX=这两个参数配置有问题。以前配置LDAP的时候没有配到过这个参数。。。

**Comment by krisbai** [comment]
> OpenLDAP 还是 ActiveDirectory?
> 
> 参考下这个
> 
> #15

你好，是LDAP，就是参考的这个配置。怀疑是LDAP_ACCOUNT_PREFIX=和LDAP_ACCOUNT_SUFFIX=这两个参数配置有问题。以前配置LDAP的时候没有配到过这个参数。。。

**Comment by mrochcn** [comment]
遇到了同样的报错

**Comment by mrochcn** [comment]
而且区/var/lib 发现日志是空的🤣
